    <!-- Generator: generate_mqttmon_inc.sh -->
    <!-- generated: 30.01.2023 16:08:10 -->
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_aqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_aqi">aeris_aqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_aqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_co-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_co">aeris_co</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_co" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_no2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_no2">aeris_no2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_no2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_o3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_o3">aeris_o3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_o3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_pm10_0-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_pm10_0">aeris_pm10_0</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_pm10_0" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_pm2_5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_pm2_5">aeris_pm2_5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_pm2_5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="aeris_so2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_so2">aeris_so2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="aeris_so2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="altimeter-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.altimeter">altimeter</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="altimeter" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="appTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.appTemp">appTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="appTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_altimeter-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_altimeter">asky_box_altimeter</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_altimeter" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_barometer">asky_box_barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_dewpoint">asky_box_dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_fan-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_fan">asky_box_fan</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_fan" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_humidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_humidity">asky_box_humidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_humidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_pressure-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_pressure">asky_box_pressure</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_pressure" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_box_temperature-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_temperature">asky_box_temperature</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_box_temperature" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_cpu_fan-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_fan">asky_cpu_fan</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_cpu_fan" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_cpu_temperature-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_temperature">asky_cpu_temperature</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_cpu_temperature" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_dome_dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_dewpoint">asky_dome_dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_dome_dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_dome_heater-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_heater">asky_dome_heater</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_dome_heater" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="asky_dome_temperature-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_temperature">asky_dome_temperature</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="asky_dome_temperature" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.barometer">barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bathroom_hqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_hqi">bathroom_hqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bathroom_hqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bathroom_rqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_rqi">bathroom_rqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bathroom_rqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bathroom_tqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_tqi">bathroom_tqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bathroom_tqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="beaufort-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.beaufort">beaufort</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="beaufort" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bedroom_hqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_hqi">bedroom_hqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bedroom_hqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bedroom_rqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_rqi">bedroom_rqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bedroom_rqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="bedroom_tqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_tqi">bedroom_tqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="bedroom_tqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="boilingTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.boilingTemp">boilingTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="boilingTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Altimeter-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Altimeter">cdc_Altimeter</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Altimeter" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Altitude-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Altitude">cdc_Altitude</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Altitude" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Barometer">cdc_Barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_DateTime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_DateTime">cdc_DateTime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_DateTime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Dewpoint">cdc_Dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_ExtraTemp1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_ExtraTemp1">cdc_ExtraTemp1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_ExtraTemp1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_FMX_10-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_FMX_10">cdc_FMX_10</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_FMX_10" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_FNX_10-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_FNX_10">cdc_FNX_10</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_FNX_10" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Latitude-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Latitude">cdc_Latitude</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Latitude" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Longitude-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Longitude">cdc_Longitude</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Longitude" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_MESS_DATUM-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_MESS_DATUM">cdc_MESS_DATUM</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_MESS_DATUM" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_OutHumidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_OutHumidity">cdc_OutHumidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_OutHumidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_OutTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_OutTemp">cdc_OutTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_OutTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Pressure-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Pressure">cdc_Pressure</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Pressure" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Quality_level-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Quality_level">cdc_Quality_level</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Quality_level" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Radiation-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Radiation">cdc_Radiation</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Radiation" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Rain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Rain">cdc_Rain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Rain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_RainDur-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_RainDur">cdc_RainDur</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_RainDur" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_RainIndex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_RainIndex">cdc_RainIndex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_RainIndex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_SolarRad-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_SolarRad">cdc_SolarRad</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_SolarRad" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_Station_id-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Station_id">cdc_Station_id</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_Station_id" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_SunshineDur-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_SunshineDur">cdc_SunshineDur</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_SunshineDur" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindDir">cdc_WindDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindDir10-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindDir10">cdc_WindDir10</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindDir10" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindGust-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindGust">cdc_WindGust</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindGust" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindGustDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindGustDir">cdc_WindGustDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindGustDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindSpeed-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindSpeed">cdc_WindSpeed</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindSpeed" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cdc_WindSpeed10-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindSpeed10">cdc_WindSpeed10</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cdc_WindSpeed10" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="cloudbase-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.cloudbase">cloudbase</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="cloudbase" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="dateTime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.dateTime">dateTime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="dateTime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_barometer_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_barometer_max">day_barometer_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_barometer_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_barometer_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_barometer_maxtime">day_barometer_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_barometer_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_barometer_min-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_barometer_min">day_barometer_min</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_barometer_min" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_barometer_mintime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_barometer_mintime">day_barometer_mintime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_barometer_mintime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="dayET-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.dayET">dayET</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="dayET" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="daymaxwind-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.daymaxwind">daymaxwind</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="daymaxwind" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_outTemp_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_avg">day_outTemp_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_outTemp_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_max">day_outTemp_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_outTemp_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_maxtime">day_outTemp_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_outTemp_min-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_min">day_outTemp_min</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_min" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_outTemp_mintime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_mintime">day_outTemp_mintime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_mintime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="dayRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.dayRain">dayRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="dayRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_rainRate_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_rainRate_max">day_rainRate_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_rainRate_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_rainRate_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_rainRate_maxtime">day_rainRate_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_rainRate_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_sunshineDur_sum-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_sunshineDur_sum">day_sunshineDur_sum</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_sunshineDur_sum" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_wind_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_wind_avg">day_wind_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_wind_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windGust_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windGust_avg">day_windGust_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windGust_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windGust_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windGust_max">day_windGust_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windGust_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windGust_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windGust_maxtime">day_windGust_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windGust_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_wind_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_wind_max">day_wind_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_wind_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_wind_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_wind_maxtime">day_wind_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_wind_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windrun_sum-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windrun_sum">day_windrun_sum</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windrun_sum" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windSpeed_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_avg">day_windSpeed_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windSpeed_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_max">day_windSpeed_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="day_windSpeed_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_maxtime">day_windSpeed_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.dewpoint">dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="ET-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.ET">ET</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="ET" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="ET24-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.ET24">ET24</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="ET24" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="eventRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.eventRain">eventRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="eventRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraHumid1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid1">extraHumid1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraHumid1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraHumid2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid2">extraHumid2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraHumid2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraHumid3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid3">extraHumid3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraHumid3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraTemp1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp1">extraTemp1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraTemp1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraTemp2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp2">extraTemp2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraTemp2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="extraTemp3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp3">extraTemp3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="extraTemp3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_cloudbase-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_cloudbase">foshk_cloudbase</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_cloudbase" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_dewpoint">foshk_dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_feelslike-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_feelslike">foshk_feelslike</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_feelslike" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_heatindex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_heatindex">foshk_heatindex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_heatindex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_interval-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_interval">foshk_interval</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_interval" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_sunhours-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_sunhours">foshk_sunhours</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_sunhours" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_sunshine-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_sunshine">foshk_sunshine</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_sunshine" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_windchill-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windchill">foshk_windchill</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_windchill" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_winddir_avg10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_winddir_avg10m">foshk_winddir_avg10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_winddir_avg10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_windgust_max10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windgust_max10m">foshk_windgust_max10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_windgust_max10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="foshk_windspeed_avg10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windspeed_avg10m">foshk_windspeed_avg10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="foshk_windspeed_avg10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="gainRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.gainRain">gainRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="gainRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="GTS-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.GTS">GTS</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="GTS" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="heatindex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.heatindex">heatindex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="heatindex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="hourRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.hourRain">hourRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="hourRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="humidex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.humidex">humidex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="humidex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="inDewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.inDewpoint">inDewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="inDewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="inHumidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.inHumidity">inHumidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="inHumidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="inTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.inTemp">inTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="inTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="interval-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.interval">interval</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="interval" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count">lightning_strike_count</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count_sum10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum10m">lightning_strike_count_sum10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count_sum2m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum2m">lightning_strike_count_sum2m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum2m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count_sum30m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum30m">lightning_strike_count_sum30m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum30m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count_sum5m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum5m">lightning_strike_count_sum5m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum5m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="lightning_strike_count_sum60m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum60m">lightning_strike_count_sum60m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum60m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="livingroom_hqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_hqi">livingroom_hqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="livingroom_hqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="livingroom_rqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_rqi">livingroom_rqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="livingroom_rqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="livingroom_tqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_tqi">livingroom_tqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="livingroom_tqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="luminosity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.luminosity">luminosity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="luminosity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="maxSolarRad-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.maxSolarRad">maxSolarRad</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="maxSolarRad" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_barometer_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_barometer_max">month_barometer_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_barometer_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_barometer_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_barometer_maxtime">month_barometer_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_barometer_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_barometer_min-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_barometer_min">month_barometer_min</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_barometer_min" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_barometer_mintime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_barometer_mintime">month_barometer_mintime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_barometer_mintime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_outTemp_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_avg">month_outTemp_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_outTemp_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_max">month_outTemp_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_outTemp_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_maxtime">month_outTemp_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_outTemp_min-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_min">month_outTemp_min</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_min" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_outTemp_mintime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_mintime">month_outTemp_mintime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_mintime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="monthRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.monthRain">monthRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="monthRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_rainRate_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_rainRate_max">month_rainRate_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_rainRate_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_rainRate_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_rainRate_maxtime">month_rainRate_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_rainRate_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_wind_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_wind_avg">month_wind_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_wind_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windGust_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windGust_avg">month_windGust_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windGust_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windGust_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windGust_max">month_windGust_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windGust_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windGust_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windGust_maxtime">month_windGust_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windGust_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_wind_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_wind_max">month_wind_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_wind_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_wind_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_wind_maxtime">month_wind_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_wind_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windSpeed_avg-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_avg">month_windSpeed_avg</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_avg" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windSpeed_max-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_max">month_windSpeed_max</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_max" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="month_windSpeed_maxtime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_maxtime">month_windSpeed_maxtime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_maxtime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="office_hqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.office_hqi">office_hqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="office_hqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="office_rqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.office_rqi">office_rqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="office_rqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="office_tqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.office_tqi">office_tqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="office_tqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_AppTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_AppTemp">om_AppTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_AppTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Barometer">om_Barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Cloudcover-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Cloudcover">om_Cloudcover</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Cloudcover" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_DateTime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_DateTime">om_DateTime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_DateTime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Dewpoint">om_Dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Et-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Et">om_Et</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Et" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_FreezinglevelHeight-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_FreezinglevelHeight">om_FreezinglevelHeight</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_FreezinglevelHeight" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_OutHumidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_OutHumidity">om_OutHumidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_OutHumidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_OutTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_OutTemp">om_OutTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_OutTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Radiation-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Radiation">om_Radiation</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Radiation" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Rain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Rain">om_Rain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Rain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Shower-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Shower">om_Shower</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Shower" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Snow-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Snow">om_Snow</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Snow" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_SnowDepth-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_SnowDepth">om_SnowDepth</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_SnowDepth" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_Weathercode-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_Weathercode">om_Weathercode</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_Weathercode" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_WindDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_WindDir">om_WindDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_WindDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_WindGust-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_WindGust">om_WindGust</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_WindGust" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="om_WindSpeed-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.om_WindSpeed">om_WindSpeed</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="om_WindSpeed" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outEquiTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outEquiTemp">outEquiTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outEquiTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outHumAbs-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outHumAbs">outHumAbs</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outHumAbs" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outHumidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outHumidity">outHumidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outHumidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outMixingRatio-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outMixingRatio">outMixingRatio</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outMixingRatio" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outSVP-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outSVP">outSVP</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outSVP" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outTemp">outTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outThetaE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outThetaE">outThetaE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outThetaE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="outVaporP-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.outVaporP">outVaporP</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="outVaporP" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_aqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_aqi">owm_aqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_aqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_co-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_co">owm_co</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_co" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_nh3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_nh3">owm_nh3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_nh3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_no-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_no">owm_no</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_no" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_no2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_no2">owm_no2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_no2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_o3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_o3">owm_o3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_o3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_pm10_0-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_pm10_0">owm_pm10_0</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_pm10_0" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_pm2_5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_pm2_5">owm_pm2_5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_pm2_5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="owm_so2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.owm_so2">owm_so2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="owm_so2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pm10_0-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pm10_0">pm10_0</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pm10_0" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pm2_5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pm2_5">pm2_5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pm2_5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Barometer">poi_Barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Cloudbase-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Cloudbase">poi_Cloudbase</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Cloudbase" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Cloudcover-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Cloudcover">poi_Cloudcover</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Cloudcover" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_DateTime-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_DateTime">poi_DateTime</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_DateTime" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Dewpoint">poi_Dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_ExtraTemp1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_ExtraTemp1">poi_ExtraTemp1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_ExtraTemp1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_OutHumidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_OutHumidity">poi_OutHumidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_OutHumidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_OutTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_OutTemp">poi_OutTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_OutTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_PresentWeather-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_PresentWeather">poi_PresentWeather</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_PresentWeather" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Radiation-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Radiation">poi_Radiation</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Radiation" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Rain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Rain">poi_Rain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Rain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_SnowDepth-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_SnowDepth">poi_SnowDepth</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_SnowDepth" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_SolarRad-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_SolarRad">poi_SolarRad</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_SolarRad" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_Visibility-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Visibility">poi_Visibility</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_Visibility" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_WindDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_WindDir">poi_WindDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_WindDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="poi_WindSpeed-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.poi_WindSpeed">poi_WindSpeed</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="poi_WindSpeed" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pressure-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pressure">pressure</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pressure" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi">pws_aqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_category">pws_aqi_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_no2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2">pws_aqi_no2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_no2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_no2_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2_category">pws_aqi_no2_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_no2_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_o3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3">pws_aqi_o3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_o3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_o3_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3_category">pws_aqi_o3_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_o3_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_pm10_0-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0">pws_aqi_pm10_0</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm10_0" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_pm10_0_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0_category">pws_aqi_pm10_0_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm10_0_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_pm2_5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5">pws_aqi_pm2_5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm2_5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="pws_aqi_pm2_5_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5_category">pws_aqi_pm2_5_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm2_5_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="radiation-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.radiation">radiation</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="radiation" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain">rain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain24-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain24">rain24</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain24" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rainRate-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rainRate">rainRate</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rainRate" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain_sum10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum10m">rain_sum10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain_sum10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain_sum2m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum2m">rain_sum2m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain_sum2m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain_sum30m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum30m">rain_sum30m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain_sum30m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain_sum5m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum5m">rain_sum5m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain_sum5m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rain_sum60m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum60m">rain_sum60m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rain_sum60m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="rxCheckPercent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.rxCheckPercent">rxCheckPercent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="rxCheckPercent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sds011_humidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_humidity">sds011_humidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sds011_humidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sds011_pm10_0-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_pm10_0">sds011_pm10_0</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sds011_pm10_0" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sds011_pm2_5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_pm2_5">sds011_pm2_5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sds011_pm2_5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sds011_temperature-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_temperature">sds011_temperature</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sds011_temperature" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="signal1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.signal1">signal1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="signal1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="signal2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.signal2">signal2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="signal2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="signal3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.signal3">signal3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="signal3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="signal5-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.signal5">signal5</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="signal5" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="signal8-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.signal8">signal8</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="signal8" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="soilMoist1-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.soilMoist1">soilMoist1</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="soilMoist1" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_altimeter-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_altimeter">solar_altimeter</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_altimeter" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_appTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_appTemp">solar_appTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_appTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_barometer">solar_barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_dewpoint-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_dewpoint">solar_dewpoint</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_dewpoint" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_heatindex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_heatindex">solar_heatindex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_heatindex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_humidex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_humidex">solar_humidex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_humidex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_humidity-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_humidity">solar_humidity</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_humidity" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_pressure-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_pressure">solar_pressure</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_pressure" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_temperature-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_temperature">solar_temperature</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_temperature" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_thswIndex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_thswIndex">solar_thswIndex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_thswIndex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_thwIndex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_thwIndex">solar_thwIndex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_thwIndex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_voltage-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_voltage">solar_voltage</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_voltage" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_voltage_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_voltage_percent">solar_voltage_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_voltage_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_wetBulb-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_wetBulb">solar_wetBulb</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_wetBulb" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="solar_windchill-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.solar_windchill">solar_windchill</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="solar_windchill" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="station_interval-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.station_interval">station_interval</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="station_interval" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine">sunshine</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine_avg10m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg10m">sunshine_avg10m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg10m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine_avg2m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg2m">sunshine_avg2m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg2m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine_avg30m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg30m">sunshine_avg30m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg30m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine_avg5m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg5m">sunshine_avg5m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg5m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshine_avg60m-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg60m">sunshine_avg60m</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg60m" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshineDur-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineDur">sunshineDur</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshineDur" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshineRadiationMin-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineRadiationMin">sunshineRadiationMin</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshineRadiationMin" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshineThreshold-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineThreshold">sunshineThreshold</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshineThreshold" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="sunshineThresholdMin-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineThresholdMin">sunshineThresholdMin</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="sunshineThresholdMin" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="thswIndex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.thswIndex">thswIndex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="thswIndex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="thwIndex-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.thwIndex">thwIndex</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="thwIndex" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="totalRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.totalRain">totalRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="totalRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="trend_asky_box_barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.trend_asky_box_barometer">trend_asky_box_barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="trend_asky_box_barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="trend_barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.trend_barometer">trend_barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="trend_barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="trend_outTemp-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.trend_outTemp">trend_outTemp</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="trend_outTemp" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="trend_solar_barometer-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.trend_solar_barometer">trend_solar_barometer</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="trend_solar_barometer" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_aqi-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_aqi">uba_aqi</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_aqi" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_aqi_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_aqi_category">uba_aqi_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_aqi_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_no2-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_no2">uba_no2</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_no2" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_no2_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_no2_category">uba_no2_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_no2_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_o3-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_o3">uba_o3</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_o3" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uba_o3_category-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uba_o3_category">uba_o3_category</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uba_o3_category" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="usUnits-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.usUnits">usUnits</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="usUnits" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="utcoffsetLMT-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.utcoffsetLMT">utcoffsetLMT</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="utcoffsetLMT" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="UV-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.UV">UV</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="UV" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="uvradiation-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.uvradiation">uvradiation</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="uvradiation" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="weekRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.weekRain">weekRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="weekRain" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wetBulb-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wetBulb">wetBulb</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wetBulb" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch1_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt">wh31_ch1_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch1_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt_percent">wh31_ch1_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch1_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig">wh31_ch1_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch1_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig_percent">wh31_ch1_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch2_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt">wh31_ch2_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch2_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt_percent">wh31_ch2_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch2_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig">wh31_ch2_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch2_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig_percent">wh31_ch2_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch3_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt">wh31_ch3_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch3_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt_percent">wh31_ch3_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch3_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig">wh31_ch3_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh31_ch3_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig_percent">wh31_ch3_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh51_ch1_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt">wh51_ch1_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh51_ch1_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt_percent">wh51_ch1_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh51_ch1_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig">wh51_ch1_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh51_ch1_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig_percent">wh51_ch1_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_batt">wh57_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_batt_percent">wh57_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_lightning_count-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_count">wh57_lightning_count</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_count" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_lightning_distance-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_distance">wh57_lightning_distance</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_distance" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_lightning_time-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_time">wh57_lightning_time</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_time" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_sig">wh57_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh57_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_sig_percent">wh57_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh57_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh65_batt-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_batt">wh65_batt</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh65_batt" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh65_batt_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_batt_percent">wh65_batt_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh65_batt_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh65_sig-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_sig">wh65_sig</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh65_sig" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="wh65_sig_percent-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_sig_percent">wh65_sig_percent</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="wh65_sig_percent" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windchill-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windchill">windchill</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windchill" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windDir">windDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windGust-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windGust">windGust</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windGust" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windGustDir-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windGustDir">windGustDir</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windGustDir" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun">windrun</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_E-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_E">windrun_E</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_E" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_ENE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_ENE">windrun_ENE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_ENE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_ESE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_ESE">windrun_ESE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_ESE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_N-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_N">windrun_N</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_N" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_NE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NE">windrun_NE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_NE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_NNE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NNE">windrun_NNE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_NNE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_NNW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NNW">windrun_NNW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_NNW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_NW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NW">windrun_NW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_NW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_S-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_S">windrun_S</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_S" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_SE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SE">windrun_SE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_SE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_SSE-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SSE">windrun_SSE</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_SSE" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_SSW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SSW">windrun_SSW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_SSW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_SW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SW">windrun_SW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_SW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_W-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_W">windrun_W</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_W" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_WNW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_WNW">windrun_WNW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_WNW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windrun_WSW-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_WSW">windrun_WSW</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windrun_WSW" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="windSpeed-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.windSpeed">windSpeed</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="windSpeed" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="yearGDD-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.yearGDD">yearGDD</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="yearGDD" rel="tooltip" title="">---</span></td>
    </tr>
    <tr>
        <th scope="row" class="mqttmon-table-body-obs"><div class="yearRain-mqttmon-rcv-dot"></div><abbr rel="tooltip" title="$obs.label.yearRain">yearRain</abbr></th>
        <td class="mqttmon-table-body-obs-val"><span class="yearRain" rel="tooltip" title="">---</span></td>
    </tr>
