#!/bin/bash
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=wetBulb --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=solar_humidex --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=solar_wetBulb --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=solar_windchill --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=solar_appTemp --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=asky_cpu_fan --type=INTEGER
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=airDensity --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=thwIndex --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=thswIndex --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=vaporPressure --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=windPressure --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=sunshineDur --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=sunshineDurOriginal --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=sunshineDurMonth --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=lightning --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=outEquiTemp --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=outHumAbs --type=REAL
#sudo echo "y" | /home/weewx/bin/wee_database --add-column=gw1100_rain_total --type=REAL
