#encoding UTF-8

<style>
.container {
  position: relative;
  width: 100%;
  overflow: hidden;
  padding-top: 70%;
}

.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
  background: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100% 100%"><text fill="%23FF0000" x="50%" y="50%" font-family="\'Lucida Grande\', sans-serif" font-size="24" text-anchor="middle">Connecting Allsky Website.... Please Wait</text></svg>') 0px 0px no-repeat;
}
</style>

<div class="entry-content allsky-outer" itemprop="text">
	<div class="row" style="padding-top:15px;">
		<div class="col-sm-12" style="padding-top:10px;">
			<div class="container">
				<iframe class="responsive-iframe" src="https://allsky.ott24.net" allowfullscreen scrolling="yes"><p>Your browser does not support iframes!</iframe>
			</div>
		</div>
	</div>
</div>
