#encoding UTF-8
<!-- Start imprint.inc -->
<div class="entry-content about-outer" itemprop="text">

    <!-- Impressum -->
    <div class="row"  style="padding-top:15px;">
        <div class="col-sm-12">
            <h1>Impressum</h1>

            <h2>Angaben gem&auml;&szlig; &sect; 5 TMG</h2>
            <p>Henry Ott<br />
            Kirchstr. 12<br />
            92729 Weiherhammer</p>

            <h2>Kontakt</h2>
            <p>Telefon: +49 (0) 9605 6694010<br />
            Telefax: +49 (0) 9605 6694064<br />
            E-Mail: postmaster@weiherhammer-wetter.de</p>

            <h2>Redaktionell verantwortlich</h2>
            <p>Henry Ott<br />
            Kirchstr. 12<br />
            92729 Weiherhammer</p>

            <p>Die im Impressum angegebenen Kontaktdaten d&uuml;rfen ausschlie&szlig;lich zur Kontaktaufnahme im direkten Zusammenhang mit dieser Webseite genutzt werden.</p>
            <p>Quelle: <a href="https://www.e-recht24.de">e-recht24.de</a></p>
        </div>
    </div>

</div>
<!-- Ende imprint.inc -->
