
            <!-- Generator: generate_topics_weewx_inc.sh -->
            <!-- generated: 21.05.2024 21:00:05 -->


                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_aqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_aqi">aeris_aqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_aqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_co-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_co">aeris_co</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_co" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_no2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_no2">aeris_no2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_no2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_o3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_o3">aeris_o3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_o3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_pm10_0">aeris_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_pm2_5">aeris_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot aeris_so2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.aeris_so2">aeris_so2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="aeris_so2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_altimeter-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_altimeter">airrohr_altimeter</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_altimeter" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_barometer">airrohr_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_bme280_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_bme280_dewpoint">airrohr_bme280_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_bme280_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_bme280_outHumidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_bme280_outHumidity">airrohr_bme280_outHumidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_bme280_outHumidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_bme280_outTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_bme280_outTemp">airrohr_bme280_outTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_bme280_outTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_dht22_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_dht22_dewpoint">airrohr_dht22_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_dht22_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_dht22_outHumidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_dht22_outHumidity">airrohr_dht22_outHumidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_dht22_outHumidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_dht22_outTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_dht22_outTemp">airrohr_dht22_outTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_dht22_outTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_pm10_0">airrohr_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_pm2_5">airrohr_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_pressure-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_pressure">airrohr_pressure</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_pressure" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_sig">airrohr_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_signal_level-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_signal_level">airrohr_signal_level</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_signal_level" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot airrohr_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.airrohr_sig_percent">airrohr_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="airrohr_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot altimeter-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.altimeter">altimeter</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="altimeter" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot appTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.appTemp">appTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="appTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_altimeter-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_altimeter">asky_box_altimeter</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_altimeter" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_barometer">asky_box_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_dewpoint">asky_box_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_fan-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_fan">asky_box_fan</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_fan" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_humidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_humidity">asky_box_humidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_humidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_pressure-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_pressure">asky_box_pressure</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_pressure" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_box_temperature-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_box_temperature">asky_box_temperature</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_box_temperature" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_cam_temperature-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_cam_temperature">asky_cam_temperature</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_cam_temperature" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_cpu_fan-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_fan">asky_cpu_fan</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_cpu_fan" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_cpu_temperature-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_temperature">asky_cpu_temperature</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_cpu_temperature" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_dome_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_dome_dewpoint">asky_dome_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_dome_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_dome_heater-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_dome_heater">asky_dome_heater</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_dome_heater" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_dome_temperature-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_dome_temperature">asky_dome_temperature</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_dome_temperature" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_sig">asky_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_signal_level-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_signal_level">asky_signal_level</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_signal_level" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot asky_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.asky_sig_percent">asky_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="asky_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.barometer">barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bathroom_hqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bathroom_hqi">bathroom_hqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bathroom_hqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bathroom_rqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bathroom_rqi">bathroom_rqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bathroom_rqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bathroom_tqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bathroom_tqi">bathroom_tqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bathroom_tqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot beaufort-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.beaufort">beaufort</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="beaufort" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bedroom_hqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bedroom_hqi">bedroom_hqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bedroom_hqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bedroom_rqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bedroom_rqi">bedroom_rqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bedroom_rqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot bedroom_tqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.bedroom_tqi">bedroom_tqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="bedroom_tqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot boilingTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.boilingTemp">boilingTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="boilingTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudbase-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudbase">cloudbase</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudbase" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_ambTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_ambTemp">cloudwatcher_ambTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_ambTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent">cloudwatcher_cloudpercent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg2m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg2m">cloudwatcher_cloudpercent_avg2m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg2m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg5m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg5m">cloudwatcher_cloudpercent_avg5m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg5m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg10m">cloudwatcher_cloudpercent_avg10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg20m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg20m">cloudwatcher_cloudpercent_avg20m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg20m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg30m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg30m">cloudwatcher_cloudpercent_avg30m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg30m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_cloudpercent_avg60m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_cloudpercent_avg60m">cloudwatcher_cloudpercent_avg60m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_cloudpercent_avg60m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_corrSkyTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_corrSkyTemp">cloudwatcher_corrSkyTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_corrSkyTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_origCloudpercent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_origCloudpercent">cloudwatcher_origCloudpercent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_origCloudpercent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_origWeathercode-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_origWeathercode">cloudwatcher_origWeathercode</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_origWeathercode" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_sig">cloudwatcher_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_signal_level-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_signal_level">cloudwatcher_signal_level</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_signal_level" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_sig_percent">cloudwatcher_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_skyTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_skyTemp">cloudwatcher_skyTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_skyTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot cloudwatcher_weathercode-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.cloudwatcher_weathercode">cloudwatcher_weathercode</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="cloudwatcher_weathercode" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp1">currentAmp1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp2">currentAmp2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp3">currentAmp3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp4">currentAmp4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp5">currentAmp5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp6-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp6">currentAmp6</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp6" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp7-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp7">currentAmp7</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp7" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp8">currentAmp8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentAmp9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentAmp9">currentAmp9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentAmp9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy1">currentEnergy1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy2">currentEnergy2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy3">currentEnergy3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy4">currentEnergy4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy5">currentEnergy5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy6-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy6">currentEnergy6</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy6" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy7-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy7">currentEnergy7</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy7" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy8">currentEnergy8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentEnergy9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentEnergy9">currentEnergy9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentEnergy9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr1">currentPwr1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr2">currentPwr2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr3">currentPwr3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr4">currentPwr4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr5">currentPwr5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr6-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr6">currentPwr6</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr6" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr7-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr7">currentPwr7</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr7" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr8">currentPwr8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot currentPwr9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.currentPwr9">currentPwr9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="currentPwr9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dateTime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dateTime">dateTime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dateTime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_barometer_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_barometer_max">day_barometer_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_barometer_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_barometer_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_barometer_maxtime">day_barometer_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_barometer_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_barometer_min-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_barometer_min">day_barometer_min</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_barometer_min" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_barometer_mintime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_barometer_mintime">day_barometer_mintime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_barometer_mintime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy1">dayEnergy1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy2">dayEnergy2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy3">dayEnergy3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy4">dayEnergy4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy5">dayEnergy5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayEnergy9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayEnergy9">dayEnergy9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayEnergy9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayET-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayET">dayET</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayET" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_lightning_strike_count_sum-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_lightning_strike_count_sum">day_lightning_strike_count_sum</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_lightning_strike_count_sum" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot daymaxwind-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.daymaxwind">daymaxwind</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="daymaxwind" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_outTemp_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_avg">day_outTemp_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_outTemp_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_max">day_outTemp_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_outTemp_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_maxtime">day_outTemp_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_outTemp_min-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_min">day_outTemp_min</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_min" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_outTemp_mintime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_outTemp_mintime">day_outTemp_mintime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_outTemp_mintime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dayRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dayRain">dayRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dayRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_rainRate_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_rainRate_max">day_rainRate_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_rainRate_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_rainRate_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_rainRate_maxtime">day_rainRate_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_rainRate_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_sunshineDur_sum-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_sunshineDur_sum">day_sunshineDur_sum</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_sunshineDur_sum" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_wind_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_wind_avg">day_wind_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_wind_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windGust_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windGust_avg">day_windGust_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windGust_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windGust_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windGust_max">day_windGust_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windGust_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windGust_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windGust_maxtime">day_windGust_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windGust_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_wind_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_wind_max">day_wind_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_wind_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_wind_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_wind_maxtime">day_wind_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_wind_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windrun_sum-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windrun_sum">day_windrun_sum</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windrun_sum" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windSpeed_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_avg">day_windSpeed_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windSpeed_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_max">day_windSpeed_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot day_windSpeed_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.day_windSpeed_maxtime">day_windSpeed_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="day_windSpeed_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp1">deviceTemp1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp2">deviceTemp2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp3">deviceTemp3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp4">deviceTemp4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp5">deviceTemp5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot deviceTemp9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.deviceTemp9">deviceTemp9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="deviceTemp9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.dewpoint">dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy1">energy1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy2">energy2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy3">energy3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy4">energy4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy5">energy5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy6-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy6">energy6</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy6" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy7-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy7">energy7</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy7" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot energy8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.energy8">energy8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="energy8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot ET-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.ET">ET</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="ET" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot ET24-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.ET24">ET24</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="ET24" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot eventRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.eventRain">eventRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="eventRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraHumid1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraHumid1">extraHumid1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraHumid1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraHumid2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraHumid2">extraHumid2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraHumid2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraHumid3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraHumid3">extraHumid3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraHumid3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraTemp1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraTemp1">extraTemp1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraTemp1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraTemp2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraTemp2">extraTemp2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraTemp2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot extraTemp3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.extraTemp3">extraTemp3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="extraTemp3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_cloudbase-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_cloudbase">foshk_cloudbase</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_cloudbase" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_dewpoint">foshk_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_feelslike-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_feelslike">foshk_feelslike</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_feelslike" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_heatindex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_heatindex">foshk_heatindex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_heatindex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_interval-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_interval">foshk_interval</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_interval" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_sunhours-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_sunhours">foshk_sunhours</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_sunhours" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_sunshine-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_sunshine">foshk_sunshine</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_sunshine" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_windchill-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_windchill">foshk_windchill</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_windchill" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_winddir_avg10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_winddir_avg10m">foshk_winddir_avg10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_winddir_avg10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_windgust_max10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_windgust_max10m">foshk_windgust_max10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_windgust_max10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot foshk_windspeed_avg10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.foshk_windspeed_avg10m">foshk_windspeed_avg10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="foshk_windspeed_avg10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot freezinglevelHeight-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.freezinglevelHeight">freezinglevelHeight</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="freezinglevelHeight" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot gainRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.gainRain">gainRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="gainRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot GTS-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.GTS">GTS</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="GTS" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot GTSdate-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.GTSdate">GTSdate</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="GTSdate" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot heap_free-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.heap_free">heap_free</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="heap_free" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot heatindex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.heatindex">heatindex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="heatindex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot hourRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.hourRain">hourRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="hourRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot humidex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.humidex">humidex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="humidex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot inDewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.inDewpoint">inDewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="inDewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot inHumidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.inHumidity">inHumidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="inHumidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot inTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.inTemp">inTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="inTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot interval-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.interval">interval</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="interval" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightningcount-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightningcount">lightningcount</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightningcount" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_distance-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_distance">lightning_distance</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_distance" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_last_det_time-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_last_det_time">lightning_last_det_time</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_last_det_time" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count">lightning_strike_count</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum2m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum2m">lightning_strike_count_sum2m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum2m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum5m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum5m">lightning_strike_count_sum5m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum5m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum10m">lightning_strike_count_sum10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum20m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum20m">lightning_strike_count_sum20m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum20m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum30m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum30m">lightning_strike_count_sum30m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum30m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot lightning_strike_count_sum60m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum60m">lightning_strike_count_sum60m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="lightning_strike_count_sum60m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot livingroom_hqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.livingroom_hqi">livingroom_hqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="livingroom_hqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot livingroom_rqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.livingroom_rqi">livingroom_rqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="livingroom_rqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot livingroom_tqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.livingroom_tqi">livingroom_tqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="livingroom_tqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot luminosity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.luminosity">luminosity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="luminosity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot maxSolarRad-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.maxSolarRad">maxSolarRad</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="maxSolarRad" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_barometer_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_barometer_max">month_barometer_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_barometer_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_barometer_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_barometer_maxtime">month_barometer_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_barometer_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_barometer_min-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_barometer_min">month_barometer_min</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_barometer_min" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_barometer_mintime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_barometer_mintime">month_barometer_mintime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_barometer_mintime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_outTemp_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_avg">month_outTemp_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_outTemp_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_max">month_outTemp_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_outTemp_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_maxtime">month_outTemp_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_outTemp_min-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_min">month_outTemp_min</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_min" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_outTemp_mintime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_outTemp_mintime">month_outTemp_mintime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_outTemp_mintime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot monthRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.monthRain">monthRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="monthRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_rainRate_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_rainRate_max">month_rainRate_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_rainRate_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_rainRate_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_rainRate_maxtime">month_rainRate_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_rainRate_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_wind_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_wind_avg">month_wind_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_wind_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windGust_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windGust_avg">month_windGust_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windGust_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windGust_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windGust_max">month_windGust_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windGust_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windGust_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windGust_maxtime">month_windGust_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windGust_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_wind_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_wind_max">month_wind_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_wind_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_wind_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_wind_maxtime">month_wind_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_wind_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windSpeed_avg-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_avg">month_windSpeed_avg</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_avg" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windSpeed_max-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_max">month_windSpeed_max</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_max" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot month_windSpeed_maxtime-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.month_windSpeed_maxtime">month_windSpeed_maxtime</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="month_windSpeed_maxtime" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot office_hqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.office_hqi">office_hqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="office_hqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot office_rqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.office_rqi">office_rqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="office_rqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot office_tqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.office_tqi">office_tqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="office_tqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_aqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_aqi">om_aqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_aqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_co-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_co">om_co</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_co" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_nh3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_nh3">om_nh3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_nh3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_no2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_no2">om_no2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_no2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_o3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_o3">om_o3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_o3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_pm10_0">om_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_pm2_5">om_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot om_so2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.om_so2">om_so2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="om_so2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outEquiTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outEquiTemp">outEquiTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outEquiTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outHumAbs-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outHumAbs">outHumAbs</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outHumAbs" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outHumidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outHumidity">outHumidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outHumidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outMixingRatio-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outMixingRatio">outMixingRatio</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outMixingRatio" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outSVP-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outSVP">outSVP</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outSVP" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outTemp">outTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outThetaE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outThetaE">outThetaE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outThetaE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot outVaporP-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.outVaporP">outVaporP</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="outVaporP" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_aqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_aqi">owm_aqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_aqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_co-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_co">owm_co</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_co" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_nh3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_nh3">owm_nh3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_nh3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_no-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_no">owm_no</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_no" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_no2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_no2">owm_no2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_no2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_o3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_o3">owm_o3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_o3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_pm10_0">owm_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_pm2_5">owm_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot owm_so2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.owm_so2">owm_so2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="owm_so2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pm10_0">pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pm2_5">pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot possibly_snow-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.possibly_snow">possibly_snow</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="possibly_snow" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pressure-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pressure">pressure</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pressure" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi">pws_aqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_category-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_category">pws_aqi_category</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_category" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_no2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2">pws_aqi_no2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_no2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_no2_category-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2_category">pws_aqi_no2_category</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_no2_category" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_o3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3">pws_aqi_o3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_o3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_o3_category-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3_category">pws_aqi_o3_category</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_o3_category" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0">pws_aqi_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_pm10_0_category-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0_category">pws_aqi_pm10_0_category</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm10_0_category" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5">pws_aqi_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot pws_aqi_pm2_5_category-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5_category">pws_aqi_pm2_5_category</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="pws_aqi_pm2_5_category" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot radiation-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.radiation">radiation</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="radiation" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain">rain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain24-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain24">rain24</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain24" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rainRate-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rainRate">rainRate</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rainRate" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum2m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum2m">rain_sum2m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum2m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum5m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum5m">rain_sum5m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum5m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum10m">rain_sum10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum20m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum20m">rain_sum20m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum20m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum30m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum30m">rain_sum30m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum30m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rain_sum60m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rain_sum60m">rain_sum60m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rain_sum60m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot relbarometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.relbarometer">relbarometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="relbarometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot rxCheckPercent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.rxCheckPercent">rxCheckPercent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="rxCheckPercent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot seasonGDD-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.seasonGDD">seasonGDD</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="seasonGDD" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot signal1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.signal1">signal1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="signal1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot signal2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.signal2">signal2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="signal2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot signal3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.signal3">signal3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="signal3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot signal5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.signal5">signal5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="signal5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot signal8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.signal8">signal8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="signal8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot snowfallHeight-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.snowfallHeight">snowfallHeight</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="snowfallHeight" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot soilMoist1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.soilMoist1">soilMoist1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="soilMoist1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_altimeter-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_altimeter">solar_altimeter</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_altimeter" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_appTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_appTemp">solar_appTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_appTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_barometer">solar_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_batt">solar_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_batt_percent">solar_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_dewpoint-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_dewpoint">solar_dewpoint</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_dewpoint" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_heatindex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_heatindex">solar_heatindex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_heatindex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_humidex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_humidex">solar_humidex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_humidex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_outHumidity-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_outHumidity">solar_outHumidity</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_outHumidity" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_outTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_outTemp">solar_outTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_outTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_pressure-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_pressure">solar_pressure</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_pressure" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_sig">solar_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_signal_level-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_signal_level">solar_signal_level</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_signal_level" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_sig_percent">solar_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_thswIndex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_thswIndex">solar_thswIndex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_thswIndex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_thwIndex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_thwIndex">solar_thwIndex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_thwIndex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_wetBulb-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_wetBulb">solar_wetBulb</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_wetBulb" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot solar_windchill-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.solar_windchill">solar_windchill</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="solar_windchill" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot station_interval-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.station_interval">station_interval</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="station_interval" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot stormRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.stormRain">stormRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="stormRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine">sunshine</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg2m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg2m">sunshine_avg2m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg2m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg5m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg5m">sunshine_avg5m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg5m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg10m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg10m">sunshine_avg10m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg10m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg20m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg20m">sunshine_avg20m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg20m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg30m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg30m">sunshine_avg30m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg30m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshine_avg60m-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg60m">sunshine_avg60m</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshine_avg60m" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshineDur-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshineDur">sunshineDur</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshineDur" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshineRadiationMin-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshineRadiationMin">sunshineRadiationMin</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshineRadiationMin" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshineThreshold-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshineThreshold">sunshineThreshold</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshineThreshold" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot sunshineThresholdMin-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.sunshineThresholdMin">sunshineThresholdMin</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="sunshineThresholdMin" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot thswIndex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.thswIndex">thswIndex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="thswIndex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot thwIndex-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.thwIndex">thwIndex</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="thwIndex" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy1-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy1">totalEnergy1</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy1" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy2">totalEnergy2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy3">totalEnergy3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy4-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy4">totalEnergy4</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy4" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy5">totalEnergy5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy6-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy6">totalEnergy6</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy6" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy7-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy7">totalEnergy7</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy7" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy8-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy8">totalEnergy8</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy8" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalEnergy9-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalEnergy9">totalEnergy9</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalEnergy9" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot totalRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.totalRain">totalRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="totalRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_airrohr_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_airrohr_barometer">trend_airrohr_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_airrohr_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_asky_box_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_asky_box_barometer">trend_asky_box_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_asky_box_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_barometer">trend_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_cloudwatcher_cloudpercent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_cloudwatcher_cloudpercent">trend_cloudwatcher_cloudpercent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_cloudwatcher_cloudpercent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_lightning_strike_count-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_lightning_strike_count">trend_lightning_strike_count</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_lightning_strike_count" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_outTemp-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_outTemp">trend_outTemp</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_outTemp" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_rain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_rain">trend_rain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_rain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_solar_barometer-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_solar_barometer">trend_solar_barometer</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_solar_barometer" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_solar_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_solar_batt">trend_solar_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_solar_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot trend_sunshine-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.trend_sunshine">trend_sunshine</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="trend_sunshine" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot txBatteryStatus-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.txBatteryStatus">txBatteryStatus</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="txBatteryStatus" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uba_aqi-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uba_aqi">uba_aqi</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uba_aqi" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uba_no2-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uba_no2">uba_no2</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uba_no2" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uba_o3-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uba_o3">uba_o3</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uba_o3" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uba_pm10_0-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uba_pm10_0">uba_pm10_0</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uba_pm10_0" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uba_pm2_5-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uba_pm2_5">uba_pm2_5</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uba_pm2_5" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot usUnits-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.usUnits">usUnits</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="usUnits" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot utcoffsetLMT-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.utcoffsetLMT">utcoffsetLMT</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="utcoffsetLMT" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot UV-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.UV">UV</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="UV" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot uvradiation-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.uvradiation">uvradiation</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="uvradiation" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot weekRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.weekRain">weekRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="weekRain" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wetBulb-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wetBulb">wetBulb</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wetBulb" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch1_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt">wh31_ch1_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch1_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt_percent">wh31_ch1_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch1_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig">wh31_ch1_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch1_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig_percent">wh31_ch1_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch1_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch2_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt">wh31_ch2_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch2_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt_percent">wh31_ch2_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch2_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig">wh31_ch2_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch2_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig_percent">wh31_ch2_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch2_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch3_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt">wh31_ch3_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch3_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt_percent">wh31_ch3_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch3_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig">wh31_ch3_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh31_ch3_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig_percent">wh31_ch3_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh31_ch3_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh51_ch1_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt">wh51_ch1_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh51_ch1_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt_percent">wh51_ch1_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh51_ch1_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig">wh51_ch1_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh51_ch1_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig_percent">wh51_ch1_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh51_ch1_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_batt">wh57_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_batt_percent">wh57_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_lightning_count-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_count">wh57_lightning_count</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_count" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_lightning_distance-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_distance">wh57_lightning_distance</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_distance" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_lightning_time-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_time">wh57_lightning_time</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_lightning_time" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_sig">wh57_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh57_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh57_sig_percent">wh57_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh57_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh65_batt-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh65_batt">wh65_batt</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh65_batt" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh65_batt_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh65_batt_percent">wh65_batt_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh65_batt_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh65_sig-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh65_sig">wh65_sig</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh65_sig" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot wh65_sig_percent-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.wh65_sig_percent">wh65_sig_percent</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="wh65_sig_percent" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windchill-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windchill">windchill</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windchill" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windDir-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windDir">windDir</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windDir" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windGust-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windGust">windGust</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windGust" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windGustDir-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windGustDir">windGustDir</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windGustDir" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun">windrun</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_E-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_E">windrun_E</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_E" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_ENE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_ENE">windrun_ENE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_ENE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_ESE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_ESE">windrun_ESE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_ESE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_N-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_N">windrun_N</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_N" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_NE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_NE">windrun_NE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_NE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_NNE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_NNE">windrun_NNE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_NNE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_NNW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_NNW">windrun_NNW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_NNW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_NW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_NW">windrun_NW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_NW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_S-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_S">windrun_S</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_S" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_SE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_SE">windrun_SE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_SE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_SSE-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_SSE">windrun_SSE</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_SSE" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_SSW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_SSW">windrun_SSW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_SSW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_SW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_SW">windrun_SW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_SW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_W-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_W">windrun_W</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_W" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_WNW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_WNW">windrun_WNW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_WNW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windrun_WSW-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windrun_WSW">windrun_WSW</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windrun_WSW" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot windSpeed-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.windSpeed">windSpeed</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="windSpeed" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot yearGDD-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.yearGDD">yearGDD</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="yearGDD" rel="tooltip" title="">---</span></td>
                </tr>
                <tr>
                    <th scope="row" class="mqttmon-table-body-obs"><div class="mqttmon-rcv-dot yearRain-mqttmon-rcv-dot" style="background-color: var(--mqttmon-rcv-dot-none);"></div><abbr rel="tooltip" title="$obs.label.yearRain">yearRain</abbr></th>
                    <td class="mqttmon-table-body-obs-val"><span class="yearRain" rel="tooltip" title="">---</span></td>
                </tr>
