#errorCatcher Echo
#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">

    <!-- Datenschutzerklärung Quelle: eRecht24 -->
    <div class="row"  style="padding-top:15px;">
        <div class="col-sm-12">
            #set $file = "privacy/content.inc"
            #if os.path.exists($file)
            <!-- Begin $file Stand: 03.02.2023 -->
            #include $file
            <!-- End $file -->
            #end if
        </div>
    </div>

    <!-- Nutzung weitere Dienste -->
    <div class="row"  style="padding-top:15px;">
        <div class="col-sm-12">
            <h1>Nutzung weiterer Dienste</h1>
            <h2>1. Plugins und Tools</h2>
            <h3>Google Web Fonts</h3>
            <p>Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten so genannte Web Fonts, die von Google bereitgestellt werden. Beim Aufruf einer Seite l&auml;dt Ihr Browser die ben&ouml;tigten Web Fonts in ihren Browsercache, um Texte und Schriftarten korrekt anzuzeigen.</p>
            <p>Die benötigten Fonts sind lokal auf dem Webserver gespeichert. Daher muss der von Ihnen verwendete Browser keine Verbindung zu den Servern von Google aufnehmen.</p>
            <p>Wenn Ihr Browser Web Fonts nicht unterstützt, wird eine Standardschrift von Ihrem Computer genutzt.</p>
            <p>Weitere Informationen zu Google Web Fonts finden Sie unter <a href="https://developers.google.com/fonts/faq" target="_blank" rel="noopener noreferrer">https://developers.google.com/fonts/faq</a> und in der Datenschutzerkl&auml;rung von Google: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy?hl=de</a>.</p>
            <h3>Font Awesome</h3>
            <p>Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten und Symbolen Font Awesome. Anbieter ist die Fonticons, Inc., 6 Porter Road Apartment 3R, Cambridge, Massachusetts, USA.</p> <p>Beim Aufruf einer Seite l&auml;dt Ihr Browser die ben&ouml;tigten Fonts in ihren Browsercache, um Texte, Schriftarten und Symbole korrekt anzuzeigen.</p>
            <p>Die benötigten Fonts sind lokal auf dem Webserver gespeichert. Daher muss der von Ihnen verwendete Browser keine Verbindung zu den Servern von Font Awesome aufnehmen.</p>
            <p>Wenn Ihr Browser Font Awesome nicht unterst&uuml;tzt, wird eine Standardschrift von Ihrem Computer genutzt.</p>
            <p>Weitere Informationen zu Font Awesome finden Sie in der Datenschutzerkl&auml;rung von Font Awesome unter: <a href="https://fontawesome.com/privacy" target="_blank" rel="noopener noreferrer">https://fontawesome.com/privacy</a>.</p>
            <h3>Erik Flowers Weather Icons</h3>
            <p>Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten und Symbolen Erik Flowers Weather Icons. Beim Aufruf einer Seite l&auml;dt Ihr Browser die ben&ouml;tigten Fonts in ihren Browsercache, um Texte, Schriftarten und Symbole korrekt anzuzeigen.</p>
            <p>Die benötigten Fonts sind lokal auf dem Webserver gespeichert. Daher muss der von Ihnen verwendete Browser keine Verbindung zu anderen Servern aufbauen.</p>
            <p>Wenn Ihr Browser Erik Flowers Weather Icons nicht unterst&uuml;tzt, wird eine Standardschrift von Ihrem Computer genutzt.</p>
            <p>Weitere Informationen zu Erik Flowers Weather Icons finden Sie unter: <a href="https://erikflowers.github.io/weather-icons/" target="_blank" rel="noopener noreferrer">https://erikflowers.github.io/weather-icons/</a>.</p>
            <h3>Vaisala Xweather API</h3>
            <p>Diese Seite nutzt zur Anzeige einer Wettervorhersage Daten der Vaisala Xweather API. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung von Vaisala Xweather unter: <a href="https://www.xweather.com/privacy" target="_blank" rel="noopener noreferrer">https://www.xweather.com/privacy</a>.</p>
            <h3>Open-Weather API</h3>
            <p>Diese Seite nutzt zur Anzeige einer Wettervorhersage Daten der Open-Meteo API. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung unter: <a href="https://open-meteo.com/en/features#terms" target="_blank" rel="noopener noreferrer">https://open-meteo.com/en/features#terms</a>.</p>
            <h3>DWD Open Data</h3>
            <p>Diese Seite nutzt zur Anzeige einer Wettervorhersage DWD Open Data. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung unter: <a href="www.dwd.de/DE/service/datenschutz/datenschutz_node.html" target="_blank" rel="noopener noreferrer">www.dwd.de/DE/service/datenschutz/datenschutz_node.html</a>.</p>
            <h3>OpenWeatherMap API</h3>
            <p>Diese Seite nutzt zur Anzeige der Luftqualit&auml;t Daten der OpenWeatherMap Air Pollution API. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung von OpenWeatherMap unter: <a href="https://openweather.co.uk/privacy-policy" target="_blank" rel="noopener noreferrer">https://openweather.co.uk/privacy-policy</a>.</p>
            <h3>Windy Widget</h3>
            <p>Diese Seite nutzt zur Anzeige aktueller Wetterbedingungen das Windy Widget. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung von Windy unter: <a href="https://account.windy.com/agreements/windy-privacy-policy" target="_blank" rel="noopener noreferrer">https://account.windy.com/agreements/windy-privacy-policy</a>.</p>
            <h3>USGS.gov Earthquake Catalog Developer API</h3>
            <p>Diese Seite nutzt zur Anzeige von Erdbeben die USGS.gov Earthquake Catalog Developer API. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung unter: <a href="https://www.usgs.gov/privacy-policies" target="_blank" rel="noopener noreferrer">https://www.usgs.gov/privacy-policies</a>.</p>
            <h3>Meteogramm von wettersoftware.de</h3>
            <p>Diese Seite nutzt zur Anzeige eines Wettervorhersage Meteogramms die Meteogrammsoftware von wettersoftware.de. Weitere Informationen zum Datenschutz von wettersoftware.de finden Sie unter: <a href="http://tools.wettersoftware.de/impressum.php" target="_blank" rel="noopener noreferrer">http://tools.wettersoftware.de/impressum.php</a>.</p>
            <h3>HighCharts</h3>
            <p>Diese Seite nutzt zur Erstellung der Charts auf der Webseite HighCharts. Weitere Informationen finden Sie in der Datenschutzerkl&auml;rung unter: <a href="https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2021/11/23101731/Highsoft-Privacy-Policy-9.0.pdf" target="_blank" rel="noopener noreferrer">https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2021/11/23101731/Highsoft-Privacy-Policy-9.0.pdf</a>.</p>
            <h3>Bootstrap, JavaScript und jQuery</h3>
            <p>Diese Webseite nutzt das Bootstrap Framework, JavaScript und das jQuery Framework zur Gestaltung der Webseite sowie zur Erstellung dynamischer Inhalte auf der Webseite. Es werden keine Daten nach Beendigung der Nutzung dieser Webseite gespeichert.</p>
            <h3>Moment.js</h3>
            <p>Diese Webseite nutzt Moment.js zur Verarbeitung von Datum- und Zeitwerten in Javascript. Es werden keine Daten nach Beendigung der Nutzung dieser Webseite gespeichert.</p>
            <p>Weitere Informationen zu Moments.js finden Sie unter: <a href="https://momentjs.com" target="_blank" rel="noopener noreferrer">https://momentjs.com</a>.</p>
            <h3>PAHO-MQTT</h3>
            <p>Zur &Uuml;bertragung der aktuellen Messwerte der Wetterstation auf diese Webseite wird das Message Queuing Telemetry Transport (MQTT) Protokoll mit der Client Software PAHO-MQTT verwendet. Es werden keine Daten nach Beendigung der Nutzung dieser Webseite gespeichert.</p>
            <h3>Cookies</h3>
            <p>Diese Webseite nutzt keine Erstellung von Cookies auf Ihrem Endger&auml;t.</p>
        </div>
    </div>
    <!-- Allgemeine Hinweise des Betreibers-->
    <div class="row"  style="padding-top:15px;">
        <div class="col-sm-12">
            #set $file = "common/general_notes.inc"
            #if os.path.exists($file)
            <!-- Begin $file -->
            #include $file
            <!-- End $file -->
            #end if
        </div>
    </div>

</div>