                                        <!-- Generator: generate_weiherhammer_mqtt_inc.sh -->
                                        <!-- generated: 07.01.2023 15:03:22 -->
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_aqi-mqtt-rec-dot"></div>&nbsp;aeris_aqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_co-mqtt-rec-dot"></div>&nbsp;aeris_co</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_co" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_no2-mqtt-rec-dot"></div>&nbsp;aeris_no2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_o3-mqtt-rec-dot"></div>&nbsp;aeris_o3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_pm10_0-mqtt-rec-dot"></div>&nbsp;aeris_pm10_0</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_pm2_5-mqtt-rec-dot"></div>&nbsp;aeris_pm2_5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_so2-mqtt-rec-dot"></div>&nbsp;aeris_so2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_so2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="altimeter-mqtt-rec-dot"></div>&nbsp;altimeter</th>
                                            <td class="mqtt-table-body-obs-val"><span class="altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="appTemp-mqtt-rec-dot"></div>&nbsp;appTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="appTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_altimeter-mqtt-rec-dot"></div>&nbsp;asky_box_altimeter</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_barometer-mqtt-rec-dot"></div>&nbsp;asky_box_barometer</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_dewpoint-mqtt-rec-dot"></div>&nbsp;asky_box_dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_fan-mqtt-rec-dot"></div>&nbsp;asky_box_fan</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_fan" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_humidity-mqtt-rec-dot"></div>&nbsp;asky_box_humidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_pressure-mqtt-rec-dot"></div>&nbsp;asky_box_pressure</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_temperature-mqtt-rec-dot"></div>&nbsp;asky_box_temperature</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_cpu_fan-mqtt-rec-dot"></div>&nbsp;asky_cpu_fan</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_cpu_fan" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_cpu_temperature-mqtt-rec-dot"></div>&nbsp;asky_cpu_temperature</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_cpu_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_dewpoint-mqtt-rec-dot"></div>&nbsp;asky_dome_dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_heater-mqtt-rec-dot"></div>&nbsp;asky_dome_heater</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_heater" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_temperature-mqtt-rec-dot"></div>&nbsp;asky_dome_temperature</th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="barometer-mqtt-rec-dot"></div>&nbsp;barometer</th>
                                            <td class="mqtt-table-body-obs-val"><span class="barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_hqi-mqtt-rec-dot"></div>&nbsp;bathroom_hqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_rqi-mqtt-rec-dot"></div>&nbsp;bathroom_rqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_tqi-mqtt-rec-dot"></div>&nbsp;bathroom_tqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="beaufort-mqtt-rec-dot"></div>&nbsp;beaufort</th>
                                            <td class="mqtt-table-body-obs-val"><span class="beaufort" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_hqi-mqtt-rec-dot"></div>&nbsp;bedroom_hqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_rqi-mqtt-rec-dot"></div>&nbsp;bedroom_rqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_tqi-mqtt-rec-dot"></div>&nbsp;bedroom_tqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="boilingTemp-mqtt-rec-dot"></div>&nbsp;boilingTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="boilingTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Altimeter-mqtt-rec-dot"></div>&nbsp;cdc_Altimeter</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Altitude-mqtt-rec-dot"></div>&nbsp;cdc_Altitude</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Altitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Barometer-mqtt-rec-dot"></div>&nbsp;cdc_Barometer</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_DateTime-mqtt-rec-dot"></div>&nbsp;cdc_DateTime</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_DateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Dewpoint-mqtt-rec-dot"></div>&nbsp;cdc_Dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_ExtraTemp1-mqtt-rec-dot"></div>&nbsp;cdc_ExtraTemp1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_ExtraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_FMX_10-mqtt-rec-dot"></div>&nbsp;cdc_FMX_10</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_FMX_10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_FNX_10-mqtt-rec-dot"></div>&nbsp;cdc_FNX_10</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_FNX_10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Latitude-mqtt-rec-dot"></div>&nbsp;cdc_Latitude</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Latitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Longitude-mqtt-rec-dot"></div>&nbsp;cdc_Longitude</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Longitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_MESS_DATUM-mqtt-rec-dot"></div>&nbsp;cdc_MESS_DATUM</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_MESS_DATUM" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_OutHumidity-mqtt-rec-dot"></div>&nbsp;cdc_OutHumidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_OutHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_OutTemp-mqtt-rec-dot"></div>&nbsp;cdc_OutTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_OutTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Pressure-mqtt-rec-dot"></div>&nbsp;cdc_Pressure</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Quality_level-mqtt-rec-dot"></div>&nbsp;cdc_Quality_level</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Quality_level" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Radiation-mqtt-rec-dot"></div>&nbsp;cdc_Radiation</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Rain-mqtt-rec-dot"></div>&nbsp;cdc_Rain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_RainDur-mqtt-rec-dot"></div>&nbsp;cdc_RainDur</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_RainDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_RainIndex-mqtt-rec-dot"></div>&nbsp;cdc_RainIndex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_RainIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_SolarRad-mqtt-rec-dot"></div>&nbsp;cdc_SolarRad</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_SolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Station_id-mqtt-rec-dot"></div>&nbsp;cdc_Station_id</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Station_id" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_SunshineDur-mqtt-rec-dot"></div>&nbsp;cdc_SunshineDur</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_SunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindDir-mqtt-rec-dot"></div>&nbsp;cdc_WindDir</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindDir10-mqtt-rec-dot"></div>&nbsp;cdc_WindDir10</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindDir10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindGust-mqtt-rec-dot"></div>&nbsp;cdc_WindGust</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindGust" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindGustDir-mqtt-rec-dot"></div>&nbsp;cdc_WindGustDir</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindGustDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindSpeed-mqtt-rec-dot"></div>&nbsp;cdc_WindSpeed</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindSpeed10-mqtt-rec-dot"></div>&nbsp;cdc_WindSpeed10</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindSpeed10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cloudbase-mqtt-rec-dot"></div>&nbsp;cloudbase</th>
                                            <td class="mqtt-table-body-obs-val"><span class="cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dateTime-mqtt-rec-dot"></div>&nbsp;dateTime</th>
                                            <td class="mqtt-table-body-obs-val"><span class="dateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayET-mqtt-rec-dot"></div>&nbsp;dayET</th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayET" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="daymaxwind-mqtt-rec-dot"></div>&nbsp;daymaxwind</th>
                                            <td class="mqtt-table-body-obs-val"><span class="daymaxwind" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayRain-mqtt-rec-dot"></div>&nbsp;dayRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="daySunshineDur-mqtt-rec-dot"></div>&nbsp;daySunshineDur</th>
                                            <td class="mqtt-table-body-obs-val"><span class="daySunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayWindrun-mqtt-rec-dot"></div>&nbsp;dayWindrun</th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayWindrun" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dewpoint-mqtt-rec-dot"></div>&nbsp;dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="ET-mqtt-rec-dot"></div>&nbsp;ET</th>
                                            <td class="mqtt-table-body-obs-val"><span class="ET" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="ET24-mqtt-rec-dot"></div>&nbsp;ET24</th>
                                            <td class="mqtt-table-body-obs-val"><span class="ET24" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid1-mqtt-rec-dot"></div>&nbsp;extraHumid1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid2-mqtt-rec-dot"></div>&nbsp;extraHumid2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid3-mqtt-rec-dot"></div>&nbsp;extraHumid3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp1-mqtt-rec-dot"></div>&nbsp;extraTemp1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp2-mqtt-rec-dot"></div>&nbsp;extraTemp2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp3-mqtt-rec-dot"></div>&nbsp;extraTemp3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_cloudbase-mqtt-rec-dot"></div>&nbsp;foshk_cloudbase</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_dewpoint-mqtt-rec-dot"></div>&nbsp;foshk_dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_feelslike-mqtt-rec-dot"></div>&nbsp;foshk_feelslike</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_feelslike" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_heatindex-mqtt-rec-dot"></div>&nbsp;foshk_heatindex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_interval-mqtt-rec-dot"></div>&nbsp;foshk_interval</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_interval" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_sunhours-mqtt-rec-dot"></div>&nbsp;foshk_sunhours</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_sunhours" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_sunshine-mqtt-rec-dot"></div>&nbsp;foshk_sunshine</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_sunshine" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windchill-mqtt-rec-dot"></div>&nbsp;foshk_windchill</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_winddir_avg10m-mqtt-rec-dot"></div>&nbsp;foshk_winddir_avg10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_winddir_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windgust_max10m-mqtt-rec-dot"></div>&nbsp;foshk_windgust_max10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windgust_max10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windspeed_avg10m-mqtt-rec-dot"></div>&nbsp;foshk_windspeed_avg10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windspeed_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="gainRain-mqtt-rec-dot"></div>&nbsp;gainRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="gainRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="GTS-mqtt-rec-dot"></div>&nbsp;GTS</th>
                                            <td class="mqtt-table-body-obs-val"><span class="GTS" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="heatindex-mqtt-rec-dot"></div>&nbsp;heatindex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="hourRain-mqtt-rec-dot"></div>&nbsp;hourRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="hourRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="humidex-mqtt-rec-dot"></div>&nbsp;humidex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="humidex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inDewpoint-mqtt-rec-dot"></div>&nbsp;inDewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="inDewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inHumidity-mqtt-rec-dot"></div>&nbsp;inHumidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="inHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inTemp-mqtt-rec-dot"></div>&nbsp;inTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="inTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="interval-mqtt-rec-dot"></div>&nbsp;interval</th>
                                            <td class="mqtt-table-body-obs-val"><span class="interval" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count-mqtt-rec-dot"></div>&nbsp;lightning_strike_count</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum10m-mqtt-rec-dot"></div>&nbsp;lightning_strike_count_sum10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum2m-mqtt-rec-dot"></div>&nbsp;lightning_strike_count_sum2m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum30m-mqtt-rec-dot"></div>&nbsp;lightning_strike_count_sum30m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum5m-mqtt-rec-dot"></div>&nbsp;lightning_strike_count_sum5m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum60m-mqtt-rec-dot"></div>&nbsp;lightning_strike_count_sum60m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_hqi-mqtt-rec-dot"></div>&nbsp;livingroom_hqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_rqi-mqtt-rec-dot"></div>&nbsp;livingroom_rqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_tqi-mqtt-rec-dot"></div>&nbsp;livingroom_tqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="luminosity-mqtt-rec-dot"></div>&nbsp;luminosity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="luminosity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="maxSolarRad-mqtt-rec-dot"></div>&nbsp;maxSolarRad</th>
                                            <td class="mqtt-table-body-obs-val"><span class="maxSolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="monthRain-mqtt-rec-dot"></div>&nbsp;monthRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="monthRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_hqi-mqtt-rec-dot"></div>&nbsp;office_hqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_rqi-mqtt-rec-dot"></div>&nbsp;office_rqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_tqi-mqtt-rec-dot"></div>&nbsp;office_tqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outEquiTemp-mqtt-rec-dot"></div>&nbsp;outEquiTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outEquiTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outHumAbs-mqtt-rec-dot"></div>&nbsp;outHumAbs</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outHumAbs" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outHumidity-mqtt-rec-dot"></div>&nbsp;outHumidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outMixingRatio-mqtt-rec-dot"></div>&nbsp;outMixingRatio</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outMixingRatio" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outSVP-mqtt-rec-dot"></div>&nbsp;outSVP</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outSVP" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outTemp-mqtt-rec-dot"></div>&nbsp;outTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outThetaE-mqtt-rec-dot"></div>&nbsp;outThetaE</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outThetaE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outVaporP-mqtt-rec-dot"></div>&nbsp;outVaporP</th>
                                            <td class="mqtt-table-body-obs-val"><span class="outVaporP" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_aqi-mqtt-rec-dot"></div>&nbsp;owm_aqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_co-mqtt-rec-dot"></div>&nbsp;owm_co</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_co" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_nh3-mqtt-rec-dot"></div>&nbsp;owm_nh3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_nh3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_no-mqtt-rec-dot"></div>&nbsp;owm_no</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_no" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_no2-mqtt-rec-dot"></div>&nbsp;owm_no2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_o3-mqtt-rec-dot"></div>&nbsp;owm_o3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_pm10_0-mqtt-rec-dot"></div>&nbsp;owm_pm10_0</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_pm2_5-mqtt-rec-dot"></div>&nbsp;owm_pm2_5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_so2-mqtt-rec-dot"></div>&nbsp;owm_so2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_so2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pm10_0-mqtt-rec-dot"></div>&nbsp;pm10_0</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pm2_5-mqtt-rec-dot"></div>&nbsp;pm2_5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Barometer-mqtt-rec-dot"></div>&nbsp;poi_Barometer</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Cloudbase-mqtt-rec-dot"></div>&nbsp;poi_Cloudbase</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Cloudcover-mqtt-rec-dot"></div>&nbsp;poi_Cloudcover</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Cloudcover" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_DateTime-mqtt-rec-dot"></div>&nbsp;poi_DateTime</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_DateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Dewpoint-mqtt-rec-dot"></div>&nbsp;poi_Dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_ExtraTemp1-mqtt-rec-dot"></div>&nbsp;poi_ExtraTemp1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_ExtraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_OutHumidity-mqtt-rec-dot"></div>&nbsp;poi_OutHumidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_OutHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_OutTemp-mqtt-rec-dot"></div>&nbsp;poi_OutTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_OutTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_PresentWeather-mqtt-rec-dot"></div>&nbsp;poi_PresentWeather</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_PresentWeather" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Radiation-mqtt-rec-dot"></div>&nbsp;poi_Radiation</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Rain-mqtt-rec-dot"></div>&nbsp;poi_Rain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_SnowDepth-mqtt-rec-dot"></div>&nbsp;poi_SnowDepth</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_SnowDepth" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_SolarRad-mqtt-rec-dot"></div>&nbsp;poi_SolarRad</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_SolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Visibility-mqtt-rec-dot"></div>&nbsp;poi_Visibility</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Visibility" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_WindDir-mqtt-rec-dot"></div>&nbsp;poi_WindDir</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_WindDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_WindSpeed-mqtt-rec-dot"></div>&nbsp;poi_WindSpeed</th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_WindSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pressure-mqtt-rec-dot"></div>&nbsp;pressure</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi-mqtt-rec-dot"></div>&nbsp;pws_aqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_category-mqtt-rec-dot"></div>&nbsp;pws_aqi_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_no2-mqtt-rec-dot"></div>&nbsp;pws_aqi_no2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_no2_category-mqtt-rec-dot"></div>&nbsp;pws_aqi_no2_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_no2_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_o3-mqtt-rec-dot"></div>&nbsp;pws_aqi_o3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_o3_category-mqtt-rec-dot"></div>&nbsp;pws_aqi_o3_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_o3_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm10_0-mqtt-rec-dot"></div>&nbsp;pws_aqi_pm10_0</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm10_0_category-mqtt-rec-dot"></div>&nbsp;pws_aqi_pm10_0_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm10_0_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm2_5-mqtt-rec-dot"></div>&nbsp;pws_aqi_pm2_5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm2_5_category-mqtt-rec-dot"></div>&nbsp;pws_aqi_pm2_5_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm2_5_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="radiation-mqtt-rec-dot"></div>&nbsp;radiation</th>
                                            <td class="mqtt-table-body-obs-val"><span class="radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain-mqtt-rec-dot"></div>&nbsp;rain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain24-mqtt-rec-dot"></div>&nbsp;rain24</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain24" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rainRate-mqtt-rec-dot"></div>&nbsp;rainRate</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rainRate" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum10m-mqtt-rec-dot"></div>&nbsp;rain_sum10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum2m-mqtt-rec-dot"></div>&nbsp;rain_sum2m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum30m-mqtt-rec-dot"></div>&nbsp;rain_sum30m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum5m-mqtt-rec-dot"></div>&nbsp;rain_sum5m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum60m-mqtt-rec-dot"></div>&nbsp;rain_sum60m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rxCheckPercent-mqtt-rec-dot"></div>&nbsp;rxCheckPercent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="rxCheckPercent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_humidity-mqtt-rec-dot"></div>&nbsp;sds011_humidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_pm10_0-mqtt-rec-dot"></div>&nbsp;sds011_pm10_0</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_pm2_5-mqtt-rec-dot"></div>&nbsp;sds011_pm2_5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_temperature-mqtt-rec-dot"></div>&nbsp;sds011_temperature</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal1-mqtt-rec-dot"></div>&nbsp;signal1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal2-mqtt-rec-dot"></div>&nbsp;signal2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal3-mqtt-rec-dot"></div>&nbsp;signal3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal5-mqtt-rec-dot"></div>&nbsp;signal5</th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal8-mqtt-rec-dot"></div>&nbsp;signal8</th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal8" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="soilMoist1-mqtt-rec-dot"></div>&nbsp;soilMoist1</th>
                                            <td class="mqtt-table-body-obs-val"><span class="soilMoist1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_altimeter-mqtt-rec-dot"></div>&nbsp;solar_altimeter</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_appTemp-mqtt-rec-dot"></div>&nbsp;solar_appTemp</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_appTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_barometer-mqtt-rec-dot"></div>&nbsp;solar_barometer</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_dewpoint-mqtt-rec-dot"></div>&nbsp;solar_dewpoint</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_heatindex-mqtt-rec-dot"></div>&nbsp;solar_heatindex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_humidex-mqtt-rec-dot"></div>&nbsp;solar_humidex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_humidex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_humidity-mqtt-rec-dot"></div>&nbsp;solar_humidity</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_pressure-mqtt-rec-dot"></div>&nbsp;solar_pressure</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_temperature-mqtt-rec-dot"></div>&nbsp;solar_temperature</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_thswIndex-mqtt-rec-dot"></div>&nbsp;solar_thswIndex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_thswIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_thwIndex-mqtt-rec-dot"></div>&nbsp;solar_thwIndex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_thwIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_voltage-mqtt-rec-dot"></div>&nbsp;solar_voltage</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_voltage" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_voltage_percent-mqtt-rec-dot"></div>&nbsp;solar_voltage_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_voltage_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_wetBulb-mqtt-rec-dot"></div>&nbsp;solar_wetBulb</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_wetBulb" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_windchill-mqtt-rec-dot"></div>&nbsp;solar_windchill</th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="stormRain-mqtt-rec-dot"></div>&nbsp;stormRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="stormRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine-mqtt-rec-dot"></div>&nbsp;sunshine</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg10m-mqtt-rec-dot"></div>&nbsp;sunshine_avg10m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg2m-mqtt-rec-dot"></div>&nbsp;sunshine_avg2m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg30m-mqtt-rec-dot"></div>&nbsp;sunshine_avg30m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg5m-mqtt-rec-dot"></div>&nbsp;sunshine_avg5m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg60m-mqtt-rec-dot"></div>&nbsp;sunshine_avg60m</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineDur-mqtt-rec-dot"></div>&nbsp;sunshineDur</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineRadiationMin-mqtt-rec-dot"></div>&nbsp;sunshineRadiationMin</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineRadiationMin" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineThreshold-mqtt-rec-dot"></div>&nbsp;sunshineThreshold</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineThreshold" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineThresholdMin-mqtt-rec-dot"></div>&nbsp;sunshineThresholdMin</th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineThresholdMin" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="thswIndex-mqtt-rec-dot"></div>&nbsp;thswIndex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="thswIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="thwIndex-mqtt-rec-dot"></div>&nbsp;thwIndex</th>
                                            <td class="mqtt-table-body-obs-val"><span class="thwIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="totalRain-mqtt-rec-dot"></div>&nbsp;totalRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="totalRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="trendBarometerCode-mqtt-rec-dot"></div>&nbsp;trendBarometerCode</th>
                                            <td class="mqtt-table-body-obs-val"><span class="trendBarometerCode" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_aqi-mqtt-rec-dot"></div>&nbsp;uba_aqi</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_aqi_category-mqtt-rec-dot"></div>&nbsp;uba_aqi_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_aqi_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_no2-mqtt-rec-dot"></div>&nbsp;uba_no2</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_no2_category-mqtt-rec-dot"></div>&nbsp;uba_no2_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_no2_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_o3-mqtt-rec-dot"></div>&nbsp;uba_o3</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_o3_category-mqtt-rec-dot"></div>&nbsp;uba_o3_category</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_o3_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="usUnits-mqtt-rec-dot"></div>&nbsp;usUnits</th>
                                            <td class="mqtt-table-body-obs-val"><span class="usUnits" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="utcoffsetLMT-mqtt-rec-dot"></div>&nbsp;utcoffsetLMT</th>
                                            <td class="mqtt-table-body-obs-val"><span class="utcoffsetLMT" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="UV-mqtt-rec-dot"></div>&nbsp;UV</th>
                                            <td class="mqtt-table-body-obs-val"><span class="UV" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uvradiation-mqtt-rec-dot"></div>&nbsp;uvradiation</th>
                                            <td class="mqtt-table-body-obs-val"><span class="uvradiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="weekRain-mqtt-rec-dot"></div>&nbsp;weekRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="weekRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wetBulb-mqtt-rec-dot"></div>&nbsp;wetBulb</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wetBulb" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_batt-mqtt-rec-dot"></div>&nbsp;wh31_ch1_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_batt_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch1_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_sig-mqtt-rec-dot"></div>&nbsp;wh31_ch1_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_sig_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch1_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_batt-mqtt-rec-dot"></div>&nbsp;wh31_ch2_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_batt_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch2_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_sig-mqtt-rec-dot"></div>&nbsp;wh31_ch2_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_sig_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch2_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_batt-mqtt-rec-dot"></div>&nbsp;wh31_ch3_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_batt_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch3_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_sig-mqtt-rec-dot"></div>&nbsp;wh31_ch3_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_sig_percent-mqtt-rec-dot"></div>&nbsp;wh31_ch3_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_batt-mqtt-rec-dot"></div>&nbsp;wh51_ch1_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_batt_percent-mqtt-rec-dot"></div>&nbsp;wh51_ch1_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_sig-mqtt-rec-dot"></div>&nbsp;wh51_ch1_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_sig_percent-mqtt-rec-dot"></div>&nbsp;wh51_ch1_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_batt-mqtt-rec-dot"></div>&nbsp;wh57_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_batt_percent-mqtt-rec-dot"></div>&nbsp;wh57_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_count-mqtt-rec-dot"></div>&nbsp;wh57_lightning_count</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_count" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_distance-mqtt-rec-dot"></div>&nbsp;wh57_lightning_distance</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_distance" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_time-mqtt-rec-dot"></div>&nbsp;wh57_lightning_time</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_time" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_sig-mqtt-rec-dot"></div>&nbsp;wh57_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_sig_percent-mqtt-rec-dot"></div>&nbsp;wh57_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_batt-mqtt-rec-dot"></div>&nbsp;wh65_batt</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_batt_percent-mqtt-rec-dot"></div>&nbsp;wh65_batt_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_sig-mqtt-rec-dot"></div>&nbsp;wh65_sig</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_sig_percent-mqtt-rec-dot"></div>&nbsp;wh65_sig_percent</th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windchill-mqtt-rec-dot"></div>&nbsp;windchill</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windDir-mqtt-rec-dot"></div>&nbsp;windDir</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windGust-mqtt-rec-dot"></div>&nbsp;windGust</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windGust" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windGustDir-mqtt-rec-dot"></div>&nbsp;windGustDir</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windGustDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun-mqtt-rec-dot"></div>&nbsp;windrun</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_ESE-mqtt-rec-dot"></div>&nbsp;windrun_ESE</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_ESE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_NW-mqtt-rec-dot"></div>&nbsp;windrun_NW</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_NW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_S-mqtt-rec-dot"></div>&nbsp;windrun_S</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_S" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SE-mqtt-rec-dot"></div>&nbsp;windrun_SE</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SSE-mqtt-rec-dot"></div>&nbsp;windrun_SSE</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SSE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SSW-mqtt-rec-dot"></div>&nbsp;windrun_SSW</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SSW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SW-mqtt-rec-dot"></div>&nbsp;windrun_SW</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_W-mqtt-rec-dot"></div>&nbsp;windrun_W</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_W" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_WNW-mqtt-rec-dot"></div>&nbsp;windrun_WNW</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_WNW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_WSW-mqtt-rec-dot"></div>&nbsp;windrun_WSW</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_WSW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windSpeed-mqtt-rec-dot"></div>&nbsp;windSpeed</th>
                                            <td class="mqtt-table-body-obs-val"><span class="windSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="yearGDD-mqtt-rec-dot"></div>&nbsp;yearGDD</th>
                                            <td class="mqtt-table-body-obs-val"><span class="yearGDD" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="yearRain-mqtt-rec-dot"></div>&nbsp;yearRain</th>
                                            <td class="mqtt-table-body-obs-val"><span class="yearRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
