                                        <!-- Generator: generate_weiherhammer_mqtt_inc.sh -->
                                        <!-- generated: 11.01.2023 09:29:18 -->
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_aqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_aqi">aeris_aqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_co-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_co">aeris_co</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_co" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_no2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_no2">aeris_no2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_o3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_o3">aeris_o3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_pm10_0-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_pm10_0">aeris_pm10_0</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_pm2_5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_pm2_5">aeris_pm2_5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="aeris_so2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.aeris_so2">aeris_so2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="aeris_so2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="altimeter-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.altimeter">altimeter</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="appTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.appTemp">appTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="appTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_altimeter-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_altimeter">asky_box_altimeter</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_barometer">asky_box_barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_dewpoint">asky_box_dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_fan-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_fan">asky_box_fan</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_fan" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_humidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_humidity">asky_box_humidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_pressure-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_pressure">asky_box_pressure</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_box_temperature-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_box_temperature">asky_box_temperature</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_box_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_cpu_fan-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_fan">asky_cpu_fan</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_cpu_fan" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_cpu_temperature-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_cpu_temperature">asky_cpu_temperature</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_cpu_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_dewpoint">asky_dome_dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_heater-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_heater">asky_dome_heater</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_heater" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="asky_dome_temperature-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.asky_dome_temperature">asky_dome_temperature</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="asky_dome_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.barometer">barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_hqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_hqi">bathroom_hqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_rqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_rqi">bathroom_rqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bathroom_tqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bathroom_tqi">bathroom_tqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bathroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="beaufort-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.beaufort">beaufort</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="beaufort" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_hqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_hqi">bedroom_hqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_rqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_rqi">bedroom_rqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="bedroom_tqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.bedroom_tqi">bedroom_tqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="bedroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="boilingTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.boilingTemp">boilingTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="boilingTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Altimeter-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Altimeter">cdc_Altimeter</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Altitude-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Altitude">cdc_Altitude</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Altitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Barometer">cdc_Barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_DateTime-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_DateTime">cdc_DateTime</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_DateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Dewpoint">cdc_Dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_ExtraTemp1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_ExtraTemp1">cdc_ExtraTemp1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_ExtraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_FMX_10-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_FMX_10">cdc_FMX_10</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_FMX_10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_FNX_10-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_FNX_10">cdc_FNX_10</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_FNX_10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Latitude-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Latitude">cdc_Latitude</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Latitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Longitude-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Longitude">cdc_Longitude</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Longitude" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_MESS_DATUM-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_MESS_DATUM">cdc_MESS_DATUM</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_MESS_DATUM" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_OutHumidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_OutHumidity">cdc_OutHumidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_OutHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_OutTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_OutTemp">cdc_OutTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_OutTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Pressure-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Pressure">cdc_Pressure</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Quality_level-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Quality_level">cdc_Quality_level</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Quality_level" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Radiation-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Radiation">cdc_Radiation</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Rain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Rain">cdc_Rain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_RainDur-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_RainDur">cdc_RainDur</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_RainDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_RainIndex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_RainIndex">cdc_RainIndex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_RainIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_SolarRad-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_SolarRad">cdc_SolarRad</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_SolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_Station_id-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_Station_id">cdc_Station_id</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_Station_id" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_SunshineDur-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_SunshineDur">cdc_SunshineDur</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_SunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindDir-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindDir">cdc_WindDir</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindDir10-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindDir10">cdc_WindDir10</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindDir10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindGust-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindGust">cdc_WindGust</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindGust" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindGustDir-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindGustDir">cdc_WindGustDir</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindGustDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindSpeed-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindSpeed">cdc_WindSpeed</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cdc_WindSpeed10-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cdc_WindSpeed10">cdc_WindSpeed10</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cdc_WindSpeed10" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="cloudbase-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.cloudbase">cloudbase</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dateTime-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.dateTime">dateTime</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="dateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayET-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.dayET">dayET</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayET" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="daymaxwind-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.daymaxwind">daymaxwind</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="daymaxwind" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.dayRain">dayRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="daySunshineDur-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.daySunshineDur">daySunshineDur</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="daySunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dayWindrun-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.dayWindrun">dayWindrun</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="dayWindrun" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.dewpoint">dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="ET-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.ET">ET</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="ET" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="ET24-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.ET24">ET24</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="ET24" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid1">extraHumid1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid2">extraHumid2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraHumid3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraHumid3">extraHumid3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraHumid3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp1">extraTemp1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp2">extraTemp2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="extraTemp3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.extraTemp3">extraTemp3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="extraTemp3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_cloudbase-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_cloudbase">foshk_cloudbase</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_dewpoint">foshk_dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_feelslike-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_feelslike">foshk_feelslike</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_feelslike" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_heatindex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_heatindex">foshk_heatindex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_interval-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_interval">foshk_interval</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_interval" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_sunhours-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_sunhours">foshk_sunhours</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_sunhours" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_sunshine-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_sunshine">foshk_sunshine</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_sunshine" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windchill-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windchill">foshk_windchill</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_winddir_avg10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_winddir_avg10m">foshk_winddir_avg10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_winddir_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windgust_max10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windgust_max10m">foshk_windgust_max10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windgust_max10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="foshk_windspeed_avg10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.foshk_windspeed_avg10m">foshk_windspeed_avg10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="foshk_windspeed_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="gainRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.gainRain">gainRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="gainRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="GTS-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.GTS">GTS</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="GTS" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="heatindex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.heatindex">heatindex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="hourRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.hourRain">hourRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="hourRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="humidex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.humidex">humidex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="humidex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inDewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.inDewpoint">inDewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="inDewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inHumidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.inHumidity">inHumidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="inHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="inTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.inTemp">inTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="inTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="interval-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.interval">interval</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="interval" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count">lightning_strike_count</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum10m">lightning_strike_count_sum10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum2m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum2m">lightning_strike_count_sum2m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum30m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum30m">lightning_strike_count_sum30m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum5m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum5m">lightning_strike_count_sum5m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="lightning_strike_count_sum60m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.lightning_strike_count_sum60m">lightning_strike_count_sum60m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="lightning_strike_count_sum60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_hqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_hqi">livingroom_hqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_rqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_rqi">livingroom_rqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="livingroom_tqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.livingroom_tqi">livingroom_tqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="livingroom_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="luminosity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.luminosity">luminosity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="luminosity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="maxSolarRad-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.maxSolarRad">maxSolarRad</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="maxSolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="monthRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.monthRain">monthRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="monthRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_hqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.office_hqi">office_hqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_hqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_rqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.office_rqi">office_rqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_rqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="office_tqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.office_tqi">office_tqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="office_tqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outEquiTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outEquiTemp">outEquiTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outEquiTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outHumAbs-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outHumAbs">outHumAbs</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outHumAbs" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outHumidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outHumidity">outHumidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outMixingRatio-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outMixingRatio">outMixingRatio</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outMixingRatio" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outSVP-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outSVP">outSVP</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outSVP" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outTemp">outTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outThetaE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outThetaE">outThetaE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outThetaE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="outVaporP-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.outVaporP">outVaporP</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="outVaporP" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_aqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_aqi">owm_aqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_co-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_co">owm_co</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_co" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_nh3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_nh3">owm_nh3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_nh3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_no-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_no">owm_no</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_no" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_no2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_no2">owm_no2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_o3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_o3">owm_o3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_pm10_0-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_pm10_0">owm_pm10_0</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_pm2_5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_pm2_5">owm_pm2_5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="owm_so2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.owm_so2">owm_so2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="owm_so2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pm10_0-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pm10_0">pm10_0</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pm2_5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pm2_5">pm2_5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Barometer">poi_Barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Cloudbase-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Cloudbase">poi_Cloudbase</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Cloudbase" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Cloudcover-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Cloudcover">poi_Cloudcover</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Cloudcover" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_DateTime-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_DateTime">poi_DateTime</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_DateTime" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Dewpoint">poi_Dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_ExtraTemp1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_ExtraTemp1">poi_ExtraTemp1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_ExtraTemp1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_OutHumidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_OutHumidity">poi_OutHumidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_OutHumidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_OutTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_OutTemp">poi_OutTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_OutTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_PresentWeather-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_PresentWeather">poi_PresentWeather</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_PresentWeather" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Radiation-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Radiation">poi_Radiation</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Rain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Rain">poi_Rain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_SnowDepth-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_SnowDepth">poi_SnowDepth</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_SnowDepth" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_SolarRad-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_SolarRad">poi_SolarRad</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_SolarRad" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_Visibility-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_Visibility">poi_Visibility</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_Visibility" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_WindDir-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_WindDir">poi_WindDir</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_WindDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="poi_WindSpeed-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.poi_WindSpeed">poi_WindSpeed</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="poi_WindSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pressure-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pressure">pressure</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi">pws_aqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_category">pws_aqi_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_no2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2">pws_aqi_no2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_no2_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_no2_category">pws_aqi_no2_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_no2_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_o3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3">pws_aqi_o3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_o3_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_o3_category">pws_aqi_o3_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_o3_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm10_0-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0">pws_aqi_pm10_0</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm10_0_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm10_0_category">pws_aqi_pm10_0_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm10_0_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm2_5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5">pws_aqi_pm2_5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="pws_aqi_pm2_5_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.pws_aqi_pm2_5_category">pws_aqi_pm2_5_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="pws_aqi_pm2_5_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="radiation-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.radiation">radiation</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="radiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain">rain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain24-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain24">rain24</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain24" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rainRate-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rainRate">rainRate</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rainRate" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum10m">rain_sum10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum2m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum2m">rain_sum2m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum30m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum30m">rain_sum30m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum5m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum5m">rain_sum5m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rain_sum60m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rain_sum60m">rain_sum60m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rain_sum60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="rxCheckPercent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.rxCheckPercent">rxCheckPercent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="rxCheckPercent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_humidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_humidity">sds011_humidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_pm10_0-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_pm10_0">sds011_pm10_0</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_pm10_0" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_pm2_5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_pm2_5">sds011_pm2_5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_pm2_5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sds011_temperature-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sds011_temperature">sds011_temperature</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sds011_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.signal1">signal1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.signal2">signal2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.signal3">signal3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal5-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.signal5">signal5</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal5" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="signal8-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.signal8">signal8</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="signal8" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="soilMoist1-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.soilMoist1">soilMoist1</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="soilMoist1" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_altimeter-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_altimeter">solar_altimeter</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_altimeter" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_appTemp-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_appTemp">solar_appTemp</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_appTemp" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_barometer">solar_barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_dewpoint-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_dewpoint">solar_dewpoint</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_dewpoint" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_heatindex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_heatindex">solar_heatindex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_heatindex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_humidex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_humidex">solar_humidex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_humidex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_humidity-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_humidity">solar_humidity</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_humidity" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_pressure-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_pressure">solar_pressure</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_pressure" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_temperature-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_temperature">solar_temperature</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_temperature" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_thswIndex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_thswIndex">solar_thswIndex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_thswIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_thwIndex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_thwIndex">solar_thwIndex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_thwIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_voltage-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_voltage">solar_voltage</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_voltage" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_voltage_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_voltage_percent">solar_voltage_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_voltage_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_wetBulb-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_wetBulb">solar_wetBulb</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_wetBulb" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="solar_windchill-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.solar_windchill">solar_windchill</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="solar_windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="stormRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.stormRain">stormRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="stormRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine">sunshine</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg10m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg10m">sunshine_avg10m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg10m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg2m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg2m">sunshine_avg2m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg2m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg30m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg30m">sunshine_avg30m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg30m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg5m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg5m">sunshine_avg5m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg5m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshine_avg60m-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshine_avg60m">sunshine_avg60m</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshine_avg60m" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineDur-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineDur">sunshineDur</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineDur" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineRadiationMin-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineRadiationMin">sunshineRadiationMin</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineRadiationMin" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineThreshold-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineThreshold">sunshineThreshold</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineThreshold" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="sunshineThresholdMin-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.sunshineThresholdMin">sunshineThresholdMin</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="sunshineThresholdMin" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="thswIndex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.thswIndex">thswIndex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="thswIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="thwIndex-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.thwIndex">thwIndex</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="thwIndex" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="totalRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.totalRain">totalRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="totalRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="trend_asky_box_barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.trend_asky_box_barometer">trend_asky_box_barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="trend_asky_box_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="trend_barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.trend_barometer">trend_barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="trend_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="trend_barometer_code-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.trend_barometer_code">trend_barometer_code</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="trend_barometer_code" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="trend_solar_barometer-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.trend_solar_barometer">trend_solar_barometer</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="trend_solar_barometer" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_aqi-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_aqi">uba_aqi</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_aqi" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_aqi_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_aqi_category">uba_aqi_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_aqi_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_no2-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_no2">uba_no2</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_no2" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_no2_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_no2_category">uba_no2_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_no2_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_o3-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_o3">uba_o3</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_o3" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uba_o3_category-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uba_o3_category">uba_o3_category</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uba_o3_category" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="usUnits-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.usUnits">usUnits</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="usUnits" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="utcoffsetLMT-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.utcoffsetLMT">utcoffsetLMT</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="utcoffsetLMT" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="UV-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.UV">UV</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="UV" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="uvradiation-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.uvradiation">uvradiation</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="uvradiation" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="weekRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.weekRain">weekRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="weekRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wetBulb-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wetBulb">wetBulb</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wetBulb" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt">wh31_ch1_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_batt_percent">wh31_ch1_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig">wh31_ch1_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch1_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch1_sig_percent">wh31_ch1_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch1_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt">wh31_ch2_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_batt_percent">wh31_ch2_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig">wh31_ch2_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch2_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch2_sig_percent">wh31_ch2_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch2_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt">wh31_ch3_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_batt_percent">wh31_ch3_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig">wh31_ch3_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh31_ch3_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh31_ch3_sig_percent">wh31_ch3_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh31_ch3_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt">wh51_ch1_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_batt_percent">wh51_ch1_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig">wh51_ch1_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh51_ch1_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh51_ch1_sig_percent">wh51_ch1_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh51_ch1_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_batt">wh57_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_batt_percent">wh57_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_count-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_count">wh57_lightning_count</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_count" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_distance-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_distance">wh57_lightning_distance</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_distance" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_lightning_time-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_lightning_time">wh57_lightning_time</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_lightning_time" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_sig">wh57_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh57_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh57_sig_percent">wh57_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh57_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_batt-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_batt">wh65_batt</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_batt" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_batt_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_batt_percent">wh65_batt_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_batt_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_sig-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_sig">wh65_sig</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_sig" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="wh65_sig_percent-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.wh65_sig_percent">wh65_sig_percent</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="wh65_sig_percent" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windchill-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windchill">windchill</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windchill" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windDir-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windDir">windDir</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windGust-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windGust">windGust</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windGust" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windGustDir-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windGustDir">windGustDir</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windGustDir" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun">windrun</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_E-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_E">windrun_E</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_E" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_ENE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_ENE">windrun_ENE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_ENE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_ESE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_ESE">windrun_ESE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_ESE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_N-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_N">windrun_N</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_N" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_NE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NE">windrun_NE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_NE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_NNE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NNE">windrun_NNE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_NNE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_NNW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NNW">windrun_NNW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_NNW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_NW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_NW">windrun_NW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_NW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_S-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_S">windrun_S</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_S" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SE">windrun_SE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SSE-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SSE">windrun_SSE</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SSE" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SSW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SSW">windrun_SSW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SSW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_SW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_SW">windrun_SW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_SW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_W-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_W">windrun_W</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_W" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_WNW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_WNW">windrun_WNW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_WNW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windrun_WSW-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windrun_WSW">windrun_WSW</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windrun_WSW" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="windSpeed-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.windSpeed">windSpeed</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="windSpeed" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="yearGDD-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.yearGDD">yearGDD</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="yearGDD" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
                                        <tr>
                                            <th scope="row" class="mqtt-table-body-obs"><div class="yearRain-mqtt-rec-dot"></div><abbr rel="tooltip" title="$obs.label.yearRain">yearRain</abbr></th>
                                            <td class="mqtt-table-body-obs-val"><span class="yearRain" data-mqttrec="0">---</span></td><!-- AJAX -->
                                        </tr>
