#encoding UTF-8

<!-- Start history.inc -->
<div class="row" style="margin-top:25px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_min_temp_title
    </div>  
    <div class="col-md-12 table-responsive">
        $min_temp_table
    </div>
</div>
<div class="row" style="margin-top:15px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_avg_temp_title
    </div>  
    <div class="col-md-12 table-responsive">
        $avg_temp_table
    </div>
</div>
<div class="row" style="margin-top:15px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_max_temp_title
    </div>  
    <div class="col-md-12 table-responsive">
        $max_temp_table
    </div>
</div>
<div class="row" style="margin-top:15px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_rain_title
    </div>  
    <div class="col-md-12 table-responsive">
        $rain_table
    </div>
</div>
<div class="row" style="margin-top:15px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_rain_days_title
    </div>  
    <div class="col-md-12 table-responsive">
        $rain_days_table
    </div>
</div>
<div class="row" style="margin-top:15px;">
    <div class="col-md-12 history-headline">
        $obs.label.history_lightning_days_title
    </div>  
    <div class="col-md-12 table-responsive">
        $lightning_days_table
    </div>
</div>
<!-- Ende history.inc -->
