#errorCatcher Echo
#encoding UTF-8
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_min_temp_title</div>
    <div class="col-xs-12 history-table-container">
        $min_temp_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_avg_temp_title</div>
    <div class="col-xs-12 history-table-container">
        $avg_temp_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_max_temp_title</div>
    <div class="col-xs-12 history-table-container">
        $max_temp_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_ice_days_title</div>
    <div class="col-xs-12 history-table-container">
        $ice_days_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_frost_days_title</div>
    <div class="col-xs-12 history-table-container">
        $frost_days_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_summer_days_title</div>
    <div class="col-xs-12 history-table-container">
        $summer_days_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_hot_days_title</div>
    <div class="col-xs-12 history-table-container">
        $hot_days_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_desert_days_title</div>
    <div class="col-xs-12 history-table-container">
        $desert_days_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_vegetation_days_title</div>
    <div class="col-xs-12 history-table-container">
        $vegetation_days_table
    </div>
</div>
<div class="row" style="margin-top:25px;">
    <div class="col-md-12 history-headline">$obs.label.history_rain_title</div>
    <div class="col-xs-12 history-table-container">
        $rain_table
    </div>
</div>
<div class="row" style="margin-top:20px;">
    <div class="col-md-12 history-headline">$obs.label.history_rain_days_title</div>
    <div class="col-xs-12 history-table-container">
        $rain_days_table
    </div>
</div>
<div class="row" style="margin-top:25px;">
    <div class="col-md-12 history-headline">$obs.label.history_windgust_title</div>
    <div class="col-xs-12 history-table-container">
        $max_wind_table
    </div>
</div>
<div class="row" style="margin-top:25px;">
    <div class="col-md-12 history-headline">$obs.label.history_lightning_days_title</div>
    <div class="col-xs-12 history-table-container">
        $lightning_days_table
    </div>
</div>
