<p style="margin-top:5px"><strong>Kreis Neustadt a.d. Waldnaab</strong></p>
<table style="vertical-align:middle"><tr style="vertical-align:middle">
<td style="width:60px"><img src="../dwd/warn_icons_50x50/warn_icons_gewitter_pre.png" alt="VORABINFORMATION SCHWERES GEWITTER"/></td>
<td><p style="font-size:100%;margin-bottom:0">VORABINFORMATION UNWETTER vor SCHWEREM GEWITTER</p>
<p style="font-size:80%">gültig vom 05.06. 12:00 bis 05.06. 22:00</p></td>
</tr></table>
<p>Ab Sonntagmittag ziehen von Westen und Südwesten teils schwere Gewitter auf. Dabei muss mit heftigem Starkregen mit Mengen zwischen 25 und 40 l/qm in kurzer Zeit, Hagel mit Korngrößen um 2 cm und schweren Sturmböen bis 95 km/h (Bft 10) gerechnet werden. Eng begrenzt sind auch orkanartige Böen um 110 km/h (Bft 11) nicht ausgeschlossen. Im Verlauf wachsen die Gewitter möglicherweise zu einem größeren Gewitterkomplex zusammen, sodass stellenweise auch um 50 l/qm Regen innerhalb weniger Stunden fallen können.

Es besteht erhöhte Gefahr vor umstürzenden Bäumen, Überflutungen und Schäden an der Infrastruktur. Auch im Bahnverkehr kann es zu Beeinträchtigungen kommen.

Im Laufe des späten Abends ziehen die unwetterartigen Gewitter nach Tschechien ab.</p>
<p style="font-size:40%">0 &ndash; VORABINFORMATION SCHWERES GEWITTER &emsp;&ndash;&emsp; 1 &ndash; Vorinformation &emsp;&ndash;&emsp; II=40 &ndash; THUNDERSTORM</p><p style="font-size:80%">Quelle: <a href="https://www.dwd.de/DE/wetter/warnungen_aktuell/warnlagebericht/bayern/warnlage_bay_node.html" target="_blank">DWD</a></p>
