<h1>Allgemeine Hinweise des Betreibers</h1>
<ol>
    <li>Diese Webseite dient grundsätzlich privaten Informationszwecken des Betreibers.</li>
    <li>Keine Gewähr für die Richtigkeit angezeigter Daten.</li>
    <li>Diese Webseite wird nicht geschäftsmässig betrieben.</li>
    <li>Der Betreiber verfolgt mit dieser Webseite keine kommerziellen Interessen.</li>
    <li>Fehler, Verstöße jeglicher Art gegen Regelungen und Gesetze oder Verletzung von Rechten Dritter auf dieser Webseite erfolgen vom Betreiber nicht vorsätzlich oder beabsichtigt grob fahrlässig.</li>
    <li>Der Betreiber bittet daher menschliche Nutzer der Webseite bei Erkennung von Verstößen jeglicher Art gegen Regelungen und Gesetze oder bei Verletzung von Rechten Dritter um sofortige Kontaktaufnahme
    über die in der Datenschutzerklärung unter "Hinweis zur verantwortlichen Stelle" hinterlegten Kontaktdaten. Bei berechtigten Hinweisen wird versucht, die Ursache umgehend zu beseitigen. Vielen Dank für die Unterstützung.
    </li>
    <li>Eine über Punkt 6 hinausgehende Nutzung der angegebenen Kontaktdaten darf ausschlie&szlig;lich zur Kontaktaufnahme im direkten Zusammenhang mit dieser Webseite erfolgen.</li>
    <li>Diese Website nutzt Links oder Verweise auf andere Webseiten oder Informationen. Der Betreiber dieser Webseite übernimmt keine Verantwortung für den Inhalt der verlinkten Webseiten
    und keine Haftung für Schäden oder Verletzungen, die aus der Nutzung – gleich welcher Art – solcher Inhalte entstehen. Insbesondere geben fremde Inhalte nicht zwingend die Meinung 
    des Betreibers dieser Website wieder. Links zu anderen Webseiten oder Informationen werden den Nutzern dieser Webseite lediglich als zusätzliche Informationsoption zur Verfügung gestellt.
    </li>
    <li>Eine über das übliche Maß der Nutzung einer privten Wetterseite hinausgehende Weiterverarbeitung der Inhalte und Daten dieser Webseite, insbesondere die automatisierte und maschinelle Verarbeitung der Inhalte und Daten dieser Webseite, ist nur den 
    vom Betreiber ausdrücklich dazu autorisierten Personen und Diensten gestattet.</li>
</ol>
