#if $Extras.has_key("show_farmers_rules") and $Extras.show_farmers_rules == '1'
                    <div class="farmers-rules">
                        <div class="row farmers-rules-title">
                        </div>
                        <div class="row farmers-rules-day">
                        </div>
                        <div class="row farmers-rules-rule">
                        </div>
                        <div class="row farmers-rules-source">
                        </div>
                    </div>
#end if