#!/bin/bash
##################################################################################################
#
# Die Wetterstation speichert Datensätze seit dem 25.08.2019 in der WeeWX Datenbank.
#
# Um Diagramme für das Jahr 2019 in der Belchertown Skin besser generieren zu können,
# enthält die weewx.archiv Tabelle dummy Datensätze für das Jahr 2019.
# Von Januar bis Juli, jeweils einen Datensatz pro Monat mit NULL Werten.
#
# Bei einem --rebuild-daily Lauf werden durch diese dummy Datensätze vom Wert her gültige
# sum=0.0, count=0, wsum=0.0, sumtime=0 Werte in den archiv_day_xxx Tabellen erzeugt.
# Werden diese Werte in Diagrammen, Tabellen etc ausgewertet, müssen sie auf NULL gesetzt werden,
# da vor dem Start der Messung keine gültigen Werte entstanden sind.
#
# 1564610400 = Thu Aug 01 2019 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)
#
##################################################################################################
DB=weewx
DB_USER=weewx
DB_PASSWD=weewx
#DB_HOST=192.168.0.182
DB_HOST=localhost
STARTDATE=1564610400
DB_EXPORT="/tmp/weewx-dump-$(date +"%Y%m%d%H%M").sql"
WHAT="${DB}.archiv_day_xxx vor dem 01.08.2019"

#TODO: sowas wie: SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'archiv_day_*';
TABLES=(
"archive_day_aeris_aqi"
"archive_day_aeris_co"
"archive_day_aeris_no2"
"archive_day_aeris_o3"
"archive_day_aeris_pm10_0"
"archive_day_aeris_pm2_5"
"archive_day_aeris_so2"
"archive_day_airDensity"
"archive_day_altimeter"
"archive_day_appTemp"
"archive_day_appTemp1"
"archive_day_as3935_lightning_distance"
"archive_day_as3935_lightning_disturber_count"
"archive_day_as3935_lightning_energy"
"archive_day_as3935_lightning_last_time"
"archive_day_as3935_lightning_noise_count"
"archive_day_as3935_lightning_strike_count"
"archive_day_asky_box_barometer"
"archive_day_asky_box_dewpoint"
"archive_day_asky_box_fan"
"archive_day_asky_box_heatindex"
"archive_day_asky_box_humidity"
"archive_day_asky_box_pressure"
"archive_day_asky_box_temperature"
"archive_day_asky_cpu_fan"
"archive_day_asky_cpu_temperature"
"archive_day_asky_dome_dewpoint"
"archive_day_asky_dome_heater"
"archive_day_asky_dome_heatindex"
"archive_day_asky_dome_temperature"
"archive_day_barometer"
"archive_day_batteryStatus1"
"archive_day_batteryStatus2"
"archive_day_batteryStatus3"
"archive_day_batteryStatus4"
"archive_day_batteryStatus5"
"archive_day_batteryStatus6"
"archive_day_batteryStatus7"
"archive_day_batteryStatus8"
"archive_day_cloudbase"
"archive_day_co"
"archive_day_co2"
"archive_day_consBatteryVoltage"
"archive_day_dewpoint"
"archive_day_dewpoint1"
"archive_day_ET"
"archive_day_extraHumid1"
"archive_day_extraHumid2"
"archive_day_extraHumid3"
"archive_day_extraHumid4"
"archive_day_extraHumid5"
"archive_day_extraHumid6"
"archive_day_extraHumid7"
"archive_day_extraHumid8"
"archive_day_extraTemp1"
"archive_day_extraTemp2"
"archive_day_extraTemp3"
"archive_day_extraTemp4"
"archive_day_extraTemp5"
"archive_day_extraTemp6"
"archive_day_extraTemp7"
"archive_day_extraTemp8"
"archive_day_forecast"
"archive_day_foshk_cloudbase"
"archive_day_foshk_dewpoint"
"archive_day_foshk_feelslike"
"archive_day_foshk_heatindex"
"archive_day_foshk_sunhours"
"archive_day_foshk_windchill"
"archive_day_foshk_winddir_avg10m"
"archive_day_foshk_windgust_max10m"
"archive_day_foshk_windspeed_avg10m"
"archive_day_gw1100_dailyrain"
"archive_day_gw1100_eventrain"
"archive_day_gw1100_hourlyrain"
"archive_day_gw1100_maxdailygust"
"archive_day_gw1100_monthlyrain"
"archive_day_gw1100_rain_total"
"archive_day_gw1100_weeklyrain"
"archive_day_gw1100_yearlyrain"
"archive_day_hail"
"archive_day_hailBatteryStatus"
"archive_day_hailRate"
"archive_day_heatindex"
"archive_day_heatindex1"
"archive_day_heatingTemp"
"archive_day_heatingVoltage"
"archive_day_humidex"
"archive_day_humidex1"
"archive_day_inDewpoint"
"archive_day_inHumidity"
"archive_day_inTemp"
"archive_day_inTempBatteryStatus"
"archive_day_leafTemp1"
"archive_day_leafTemp2"
"archive_day_leafWet1"
"archive_day_leafWet2"
"archive_day_lightning_distance"
"archive_day_lightning_disturber_count"
"archive_day_lightning_energy"
"archive_day_lightning_last_time"
"archive_day_lightning_noise_count"
"archive_day_lightning_strike_count"
"archive_day_luminosity"
"archive_day_maxSolarRad"
"archive_day_nh3"
"archive_day_no2"
"archive_day_noise"
"archive_day_o3"
"archive_day_outEquiTemp"
"archive_day_outHumAbs"
"archive_day_outHumidity"
"archive_day_outTemp"
"archive_day_outTempBatteryStatus"
"archive_day_owm_aqi"
"archive_day_owm_co"
"archive_day_owm_nh3"
"archive_day_owm_no"
"archive_day_owm_no2"
"archive_day_owm_o3"
"archive_day_owm_pm10_0"
"archive_day_owm_pm2_5"
"archive_day_owm_so2"
"archive_day_pb"
"archive_day_pm1_0"
"archive_day_pm10_0"
"archive_day_pm2_5"
"archive_day_pressure"
"archive_day_pws_aqi"
"archive_day_pws_aqi_category"
"archive_day_pws_aqi_no2"
"archive_day_pws_aqi_no2_category"
"archive_day_pws_aqi_o3"
"archive_day_pws_aqi_o3_category"
"archive_day_pws_aqi_pm10_0"
"archive_day_pws_aqi_pm10_0_category"
"archive_day_pws_aqi_pm2_5"
"archive_day_pws_aqi_pm2_5_category"
"archive_day_radiation"
"archive_day_rain"
"archive_day_rainBatteryStatus"
"archive_day_rainRate"
"archive_day_referenceVoltage"
"archive_day_rxCheckPercent"
"archive_day_sds011_humidity"
"archive_day_sds011_pm10_0"
"archive_day_sds011_pm2_5"
"archive_day_sds011_temperature"
"archive_day_signal1"
"archive_day_signal2"
"archive_day_signal3"
"archive_day_signal4"
"archive_day_signal5"
"archive_day_signal6"
"archive_day_signal7"
"archive_day_signal8"
"archive_day_snow"
"archive_day_snowBatteryStatus"
"archive_day_snowDepth"
"archive_day_snowMoisture"
"archive_day_snowRate"
"archive_day_so2"
"archive_day_soilMoist1"
"archive_day_soilMoist2"
"archive_day_soilMoist3"
"archive_day_soilMoist4"
"archive_day_soilTemp1"
"archive_day_soilTemp2"
"archive_day_soilTemp3"
"archive_day_soilTemp4"
"archive_day_solar_appTemp"
"archive_day_solar_barometer"
"archive_day_solar_dewpoint"
"archive_day_solar_heatindex"
"archive_day_solar_humidex"
"archive_day_solar_humidity"
"archive_day_solar_pressure"
"archive_day_solar_temperature"
"archive_day_solar_voltage"
"archive_day_solar_wetBulb"
"archive_day_solar_windchill"
"archive_day_sunshine"
"archive_day_sunshineDur"
"archive_day_supplyVoltage"
"archive_day_thswIndex"
"archive_day_thwIndex"
"archive_day_txBatteryStatus"
"archive_day_uba_aqi"
"archive_day_uba_aqi_category"
"archive_day_uba_no2"
"archive_day_uba_no2_category"
"archive_day_uba_o3"
"archive_day_uba_o3_category"
"archive_day_UV"
"archive_day_uvBatteryStatus"
"archive_day_vaporPressure"
"archive_day_wetBulb"
"archive_day_wh57_batt"
"archive_day_wh65_batt"
"archive_day_wind"
"archive_day_windBatteryStatus"
"archive_day_windchill"
"archive_day_windDir"
"archive_day_windGust"
"archive_day_windGustDir"
"archive_day_windPressure"
"archive_day_windrun"
"archive_day_windSpeed"
)

echo ""
read -r -p "Datenbank ${DB} vorher sichern? (y/n) [y]? " response
if [[ "$response" =~ ^([nN])$ ]]; then
    echo "Datenbank ${DB} wurde NICHT gesichert."
else
    echo "Datenbank ${DB} wird in ${DB_EXPORT} gesichert..."
    sudo mysqldump --single-transaction -v -h${DB_HOST} -u${DB_USER} -p${DB_PASSWD} ${DB} >${DB_EXPORT}
    RET=$?
    if [ ${RET} -ne 0 ]; then
        echo "Fehler bei Sicherung, Code=${RET}. Skript wird abgebrochen!"
        exit ${RET}
    fi
    echo "OK."
fi

echo ""
echo "Achtung! Werte in den Tabellen ${WHAT} werden auf NULL gesetzt."
read -r -p "Weiter (y/n) [n]? " response
if [[ "$response" =~ ^([yY]|[jJ])$ ]]; then
    echo "Update der Tabellen ${WHAT} wird gestartet..."
    for TABLE in "${TABLES[@]}"
    do
        echo "Update in ${DB}.${TABLE}..."
        mysql -h${DB_HOST} -u${DB_USER} -p${DB_PASSWD} -v -e "UPDATE ${DB}.${TABLE} SET sum=NULL, count=0, wsum=NULL, sumtime=0 WHERE dateTime<${STARTDATE};"
        RET=$?
        if [ ${RET} -ne 0 ]; then
            echo "Fehler beim Update, Code=${RET}. Skript wird abgebrochen!"
            exit ${RET}
        fi
        echo "OK."
    done
else
    echo "Datensätze wurden NICHT geändert."
fi

echo -e "\nSkript abgeschlossen."